### ISSUE TITLE
Report which steps are being executed

### ISSUE THREAD

**Issue by cressie176** [acuminous/yadda#10]
It can be hard to debug what's going on during a failing test. It would help if I could see the steps that Yadda was executing. My preferred way to implement this is to fire an event on the following conditions...

Yadda: start, success, error
Interpreter: start, success, error
Macro: start, success, error

**Comment by Andras001** [comment]
Hi, the eventbus is a good solution, but it lists all the steps when calling this in the first step. It should list the current step only, in each given/when/then step.
