### ISSUE TITLE
Only pass a handler to Mocha if a handler is defined

### ISSUE THREAD

**Issue by simoami** [acuminous/yadda#104]
In Mocha, it you define an "it" step without a handler function, the step is colored in blue and marked as non-implemented / skipped.

Similarly, with Yadda, I want the following:
```
library.given('test step');
```
to be converted to:
```
it('Given test step');
```
I looked at the code handling calls to `it` in Yadda but didn't find an easy way to do it.

Ideally, if the handler reference is available, one could do something like:
```
function it_async(title, subject, iterator, fn) {
        var _it = getIt(subject.annotations);
        _it(title, fn && function(done) {
            iterator(subject, done);
        });
 }
```

**Comment by cressie176** [comment]
Closing as I'm not getting any time for the redesign. Likely to be a different project if I do.
