### ISSUE TITLE
mocha-webdriver example not working in windows

### ISSUE THREAD

**Issue by nzdunic** [acuminous/yadda#109]
Hi again

Form the front page....

"The webdriver example may fail depending on how google detects your locale."

You're right.  They all timeout.  Be nice to get it working though.  My environment is Windows 8.1

Cheers,

Nick

**Comment by kblcuk** [comment]
@cressie176, probably irrelevant to original issue, but 'almost the same': experiencing the same behaviour on OS X and Linux as well with latest selenium-webdriver (2.45.1 at the moment of writing).

Example just stalls after browser is run, doesn't get further than initial 'data;' page.
Works fine with selenium-webdriver 2.44.0.
Browsers in question are latest Chrome and FireFox, so doesn't seem to be browser-specific.

**Comment by cressie176** [comment]
Mmmm. Sounds worrying. I'm flat out right now, but thanks for reporting. Will take a look when a have a spare hour

**Comment by kblcuk** [comment]
Sure, and no rush :) Also let me know if you need more info on environment/etc.

**Comment by cressie176** [comment]
I can reproduce. I'll dig into it a little more and if I don't make any progress raise an issue at https://github.com/SeleniumHQ/selenium

**Comment by kblcuk** [comment]
Ok, thanks for the news!

**Comment by cressie176** [comment]
As suggested in https://github.com/SeleniumHQ/selenium/issues/567 the following modification to mocha-webdriver fixes the problem. I'll update the examples accordingly. Thanks for raising.
```javascript
before(function(done) {
    executeInFlow(function() {
        driver = new webdriver.Builder().usingServer().withCapabilities({'browserName': 'chrome'}).build();
        driver.manage().timeouts().implicitlyWait(10000);
    }, done);
});
```

**Comment by kblcuk** [comment]
Great, will do the same with our code. Thanks again!

**Comment by kblcuk** [comment]
Just to confirm -- the modification (wrapping driver creation with `executeInFlow`) worked for me. So I guess this is solved.

**Comment by cressie176** [comment]
Updated the examples with the webdriver fix. Closing as I'm not going to fix the flakey windows tests - don't have a windows machine anymore
