### ISSUE TITLE
clearer documentation

### ISSUE THREAD

**Issue by jwoudenberg** [acuminous/yadda#111]
I'm trying to use Yadda with Mocha and am havving some trouble understanding how Yadda works. Take the following snippet from your readme, which we also use to run our tests.

```
var Yadda = require('yadda');
Yadda.plugins.mocha.AsyncStepLevelPlugin.init();

new Yadda.FeatureFileSearch('features').each(function(file) {

    // Previously features(file, function(feature))
    featureFile(file, function(feature) {

        var library = require('./bottles-library');
        var yadda = new Yadda.Yadda(library);

        scenarios(feature.scenarios, function(scenario) {
            steps(scenario.steps, function(step, done) {
                yadda.yadda(step, done);
            })
        });
    });
});
```

Looking at it, I can only guess what the following might be doing:
- featureFile (global?)
- scenarios (global?)
- steps (global?)
- yadda.yadda

Some of these things I can sort of guess what they might be doing, but having some definitions would be nice.

Especially the yadda().yadda().yadda() that is encountered in the readme several times, often invoked with different arguments, is pretty obscure for a new user to the project and not explained anywhere as far as I can see.

Could you perhaps add some api documentation, describing the interface of a yadda instance, yadda library, yadda step, etc? Thanks!

**Comment by cressie176** [comment]
Added a gitbook
