### ISSUE TITLE
Example Tables - use them for fixture setup

### ISSUE THREAD

**Issue by nzdunic** [acuminous/yadda#112]
A good feature would be to use an Example table as input into a fixture (part of background perhaps)

Essentially its the test data to use.  This could be done in the fixture code, but it would be nice to actually have it documented in the feature file instead.

I may have missed another feature that does this already.  Let me know if I have and apologies if I have done that.

I tend to think if not then there possible is some reuse from Example Table.

Thanks,

Nick

**Comment by cressie176** [comment]
OK to close?

**Comment by teamzone** [comment]
Yes
