### ISSUE TITLE
`ReferenceError: featureFile is not defined` when exucting with `mocha --recrusive`

### ISSUE THREAD

**Issue by pbuyle** [acuminous/yadda#130]
On my project, U use Mocha to run both Yadda tests and Unit testing of my components, so I end up with the following file strcutures
```
tests/
tests/features.js
tests/features/
tests/features/<feature>.feature
tests/features/steps
tests/features/steps/<steps>.js
test/<component_type>/<component>.js
```
```features.js``` is Mocha runner for Yadda as documented in the README. When running mocha with a plain ```mocha``` command, Yadda tests are executed fine. However, since the components test are deeper in the ```/tests``` folder, they are not executed. But when I run Mocha with ```mocha --recursive``` I get the following error:
```
ReferenceError: featureFile is not defined
    at [...]/test/features.js:11:3
    at Array.forEach (native)
    at each ([...]/node_modules/yadda/lib/FileSearch.js:33:21)
    at Object.<anonymous> (/[...]/test/features.js:10:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [...]/node_modules/mocha/lib/mocha.js:184:27
    at Array.forEach (native)
    at Mocha.loadFiles [...]/node_modules/mocha/lib/mocha.js:181:14)
    at Mocha.run ([...]/node_modules/mocha/lib/mocha.js:393:31)
    at Object.<anonymous> ([...]/node_modules/mocha/bin/_mocha:380:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3
```

**Comment by cressie176** [comment]
I have a theory. I think something in one of your sub directories must be reseting the global scope. This would explain: 

a. why you couldn't reproduce with the 130 branch
b. why you only get the error when running with --recursive

What happens if you move ```Yadda.plugins.mocha.StepLevelPlugin.init();``` down a few line to
```bash
new Yadda.FeatureFileSearch('./test/features').each(function(file) {
  Yadda.plugins.mocha.StepLevelPlugin.init();
  featureFile(file, function(feature) {
```

**Comment by cressie176** [comment]
Any luck?

**Comment by pbuyle** [comment]
Sorry for the delay. I tried mocing the `Yadda.plugins.mocha.StepLevelPlugin.init();` inside the `foreach` callback, it does not solve the issue. I tried with the latest release and a checkout of the issue-130 branch.

In addition to my Yadda feature test, I also have a standard Mocha test suite (for unit testing of the a componenet of my application). Inside this test suite, I'm loading RequireJS and initialize a test environement from a separated file. Removing the `require()` to this file solve the Yadda issue. Here is the content of that file: 
```
"use strict";
var requirejs = require('requirejs')
  ,path = require('path')
  ,_ = require('lodash')
  ,cpt = 0
  ,jsdom = require("jsdom");

var defaultStubs = {

};

// Load browser compatibility lib stuff.
global.btoa = require('btoa');
global.atob = require('atob');

module.exports = function(stubs) {
  global.window = jsdom.jsdom("<html/>").parentWindow;
  // Register stubs.
  _.chain(stubs || {}).extend(defaultStubs).each(function(value, name) {
    requirejs.define(name, function() {return value;});
  });
  var config = require('../js/require-config');
  config.baseUrl = __dirname + '/../js';
  config.nodeRequire = require;
  config.context = __filename + (cpt++);
  config.deps = ['jquery'];
  config.callback = function (jQuery) {
    var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
    jQuery.support.cors = true;
    jQuery.ajaxSetup({
      xhr: function() {
        return new XMLHttpRequest();
      }
    });
  }
  return requirejs.config(config);
}

```

**Comment by cressie176** [comment]
Found the problem.

I check for the existince of a "window" object to determine whether yadda is being run from node, phantom or a browser...

https://github.com/acuminous/yadda/blob/master/lib/Platform.js
https://github.com/acuminous/yadda/blob/4a1bc86a5a2d70686541a9aaa7d54984013e0c62/lib/plugins/mocha/AsyncScenarioLevelPlugin.js#L29

In your case global.window is being set to jdom, and consequently the featureFile method is being added to 'window' instead of 'global'.

I think the only reason I do this check in the mocha plugin is because I use mocha for testing yadda, and need to assign the methods to another object. You can probably force the plugin to use GLOBAL by passing it in as an option. Will take a better look later and paste an example.

**Comment by cressie176** [comment]
I think changing your StepLevelPlugin initialisation line to
```js
Yadda.plugins.mocha.StepLevelPlugin.init({container: global});
```
should do thie job

**Comment by cressie176** [comment]
OK to close?

**Comment by pbuyle** [comment]
Yes.
