### ISSUE TITLE
Feature: finally callback

### ISSUE THREAD

**Issue by prokls** [acuminous/yadda#132]
Hi,

we have the following usecase:
consider a set of Given, When and Then statements. When statements specify that several messages are sent to a web service. Then statements check whether certain data gets stored in the web service. Now for our implementation we need a callback to handle the open connection. Specifically we want to open the connection when the scenario test starts and the connection has to be closed when the scenario finishes.

For us it suffices that opening the connection is modeled by a single given clause and we call one callback which opens the connection. But closing the connection requires one callback which is called in all Then statements. Furthermore an oracle has to tell us when the callback is called "the last time".

So using the source code from the tutorial, I would like to have a "finally" method like this:

```js
var assert = require('assert');
var English = require('yadda').localisation.English;
var Wall = require('../../lib/wall'); // The library that you wish to test
var connection = new DatabaseConnection('127.0.0.1', 1234);

module.exports = (function() {
  return English.library()
    .given("$NUM green bottles are standing on the wall", function(number, next) {
       wall = new Wall(number);
       connection.open();
       next();
    })
    .when("$NUM green bottle accidentally falls", function(number, next) {
       wall.fall(number);
       next();
    })
    .then("there are $NUM green bottles standing on the wall", function(number, next) {
       assert.equal(number, wall.bottles);
       next();
    })
    .finally(function () {
       connection.close();
    });
})();
```

**Comment by cressie176** [comment]
I attempted before / after methods in an earlier version of yadda, but abandoned them due to the difficulty of ensuring the 'after' method was always executed. Instead I run any teardown code from my test runner (e.g. mocha).

It's still reasonable to put the teardown functions in your step libraries though. A rough example...

```bash
var assert = require('assert');
var English = require('yadda').localisation.English;
var Wall = require('../../lib/wall'); // The library that you wish to test
var connection = new DatabaseConnection('127.0.0.1', 1234);

module.exports = (function() {
  var library = English.library()
    .given("$NUM green bottles are standing on the wall", function(number, next) {
       wall = new Wall(number);
       connection.open();
       next();
    })
    .when("$NUM green bottle accidentally falls", function(number, next) {
       wall.fall(number);
       next();
    })
    .then("there are $NUM green bottles standing on the wall", function(number, next) {
       assert.equal(number, wall.bottles);
       next();
    });

    library.teardown = function () {
       connection.close();
    });

   return library;
})();

**Comment by prokls** [comment]
Thank you for your response and sorry for my late reply :-)

We implemented your suggestion and it worked splendently. No need for a feature in Yadda!
