### ISSUE TITLE
Conditional block

### ISSUE THREAD

**Issue by mistic100** [acuminous/yadda#135]
Ok I know what you think : unit/behaviour tests should be immutable or whatever so conditional blocks is a non-sense.

I totally agree :-)

Now I have a project where I would like to use a tool like Yadda to write automation scenarios. This project for now is not much more than an idea : I want to create a software like jDownloader but in NodeJS/PhantomJS. Scenarios will be used to describe how to interact with direct download websites.

A basic scenario would be :
```
Click on "Download" button  
If "Download limit reached" message is displayed  
   The file cannot be downloaded
Else
   Download the file "Your file is ready"
```

Is this possible with Yadda (with some tweaks) ? Does anyone know another library with such feature ?
Thank you :-)

**Comment by cressie176** [comment]
I've often wanted to do something similar. You *can* do this type of thing with yadda, but it's not especially nice, and will get exponentially uglier with more complicated scenarios. Consider the slightly modified scenario...

```
Click on the "Download" button  
If the "Download limit reached" message is displayed  
then the file cannot be downloaded
Otherwise the "Your file is ready" message is displayed
and the file can be download
```

the steps would look something like this...

```js
.define('(?:If|Otherwise) the "$message" message is displayed', function(message, next) {
    if messageDisplayed(message, function(err, result) {
        flags[message]= true
        next(err, result);
    }) 
...
})
.then('the file cannot be downloaded. function(next) {
   if (flags[''Download limit reached"]) return next();
   assert(cannotDownloadFile());
})
.then('the file cannot be downloaded. function(next) {
   if (flags[''Your file is ready"]) return next();
   assert(canDownloadFile());
})
```

What the above doesn't verify that exactly one of those messages was displayed. If would pass incorrectly if neither message were displayed or if both were displayed (providing the file could be downloaded. You could work around this by using a Flags object which understood about mutually exclusive flags, and with a final step which checked that at least one of the flags had been set.

As I said - it's not nice

**Comment by mistic100** [comment]
Will be difficult to make something bulletproof then (if I successfully create the core of the app I want "anyone" to be able to create download scenario for any DDL website)

**Comment by cressie176** [comment]
Your best option then is to poke around the Yadda source and pillage what you need. At its core Yadda is just a library for matching a string 


> "100 green bottles standing on a wall" 

to the best fitting template

1. /(\d+) green bottles standing on a wall/
2. /if (\d+) green bottle(?:s?) should accidentally fall/
3. /there will be (\d+) bottles standing on the wall/

and executing the associated function with parameters parsed from the string

```bash
function setupWall(n) {
   wall = new Wall(); 
   for (var i = 0; i < n; i++) { 
      wall.add(new Bottle()) }
   }
}
```

The [Interpreter](https://github.com/acuminous/yadda/blob/master/lib/Interpreter.js) class is the best place to start

**Comment by mistic100** [comment]
I guess parsing Yadda is much more simple than what I want, conditional blocks would need some AST to be fully functional

perhaps I should just stick to plain js with a bunch of helpers

thank for your time
