### ISSUE TITLE
Async executions of steps

### ISSUE THREAD

**Issue by terraqout** [acuminous/yadda#139]
Hello everybody, I'm quite excited with this cucumber port. It's really the best I've ever seen in testing. But is there any way to call your step asynchronously?
I have multiple API calls in one scenario and their queue isn't important.

Any clarifications appreciated

**Comment by cressie176** [comment]
Yadda doesn't provide this, but you could do it using an async queue. Each step would put a message to the queue, and the last step would wait for the queue to drain.

**Comment by cressie176** [comment]
OK to close?

**Comment by terraqout** [comment]
Get it. Thanks
