### ISSUE TITLE
other_macro.is_identified_by is not a function

### ISSUE THREAD

**Issue by arielschiavoni** [acuminous/yadda#140]
Hi there,

I got this error when define_macro function is trying to check for a duplicated macro.
It seems that the custom array `$()` is not working properly when a macro is created and pushed to it.
For some reason some times this array does not the contain macro instances but just numbers.

Just to identify/show the problem I added a built-in array called `myMacros` and pushed macros instances to both arrays.

Please see the screenshots below: 
 
![yadda_01](https://cloud.githubusercontent.com/assets/1364564/7201970/f7b1c56c-e50d-11e4-9ed9-bf0a77015fb2.png)
![yadda_02](https://cloud.githubusercontent.com/assets/1364564/7201968/f7aff296-e50d-11e4-9e83-7b82c2e52c35.png)
![yadda_03](https://cloud.githubusercontent.com/assets/1364564/7201969/f7b00614-e50d-11e4-8e5a-c39d04fa64cd.png)

**Comment by cressie176** [comment]
That's pretty special. Do you get this error consistently? Can you describe your environment, i.e. node version, operating system, test running (e.g. mocha). Also any code showing how you invoke yadda would be helpful. Thanks.

**Comment by cressie176** [comment]
Are you still experiencing the problem?

**Comment by arielschiavoni** [comment]
Hi, sorry for the late reply. I am still experiencing the issue. I could fix the issue in my [fork](https://github.com/arielschiavoni/yadda/commit/58c6c2ae240c17ddcdda8e6096cfa62e96e67cc3) by simply adding a try catch. I am not sure why it solves the problem, if you are ok with the fix I can send you a PR.

Another thing I noticed is that the bug starts happening when I have some considerable amount of tests, I mean  +100 .

Environment:

- yadda version: ^0.11.5
- node version: currently v0.12.3 but it was also failing with 0.10.x
- operating system: OSX
- test runner:  karma-mocha

This is the way I am currently using yadda:

I created a runner.js module that exports a `run` function that will be invoked for every feature

```js
// runner.js
var yadda = require('yadda');
// configure mocha plugin for yadda
yadda.plugins.mocha.StepLevelPlugin.init();

// we are going to use english for our feature files
var English = yadda.localisation.English;

var dictionary = require('./dictionary');
// create library based on English that will be extended
// with our step definitions
var library = English.library(dictionary);

// context shared across all scenarios
var scenarioContext = require('./scenario-context.js');

// extend current library with our step definitions and share context
require('./steps/steps')(library);

// prepare parser
var FeatureParser = yadda.parsers.FeatureParser;
// configure parser to use English
var parser = new FeatureParser(English);

// create the yadda runner with our library

// define a run function that will be executed for every feature
var run = function(featureText) {
	// import and parse feature file
	var feature = parser.parse(featureText);
	var runner = new yadda.Yadda(library);

	scenarios(feature.scenarios, function(scenario) {
		var context = scenarioContext();
		steps(scenario.steps, function(step, done) {
			runner.run(step, context, done);
		});
	});
};

module.exports = run;
```

```js
// test.js
var run = require('./runner');
// the next require imports the feature text and feeds the run function 
run(require('./features/some.feature'));
```

- it seems that `$` is not overwritten (I has Array.js's content)

$.toString()
```js
function (obj) {

    function ensure_array(obj) {
        var array = obj ? [].concat(obj) : [];
        array.in_array = fn.curry(array, in_array, array);
        array.each = fn.curry(array, each, array);
        array.each_async = fn.curry(array, each_async, array);
        array.collect = fn.curry(array, collect, array);
        array.flatten = fn.curry(array, flatten, array);
        array.inject = fn.curry(array, inject, array);
        array.push_all = fn.curry(array, push_all, array);
        array.find_all = fn.curry(array, find_all, array);
        array.find = fn.curry(array, find, array);
        array.naked = fn.curry(array, naked, array);
        return array;
    }

    function is_array(obj) {
        return Object.prototype.toString.call(obj) === '[object Array]';
    }
   //...
   //...
}
```

**Comment by cressie176** [comment]
Thanks. I'll try and reproduce

**Comment by cressie176** [comment]
Sorry for the delay - really busy with the day job. I've created a [branch](https://github.com/acuminous/yadda/tree/issue-140) with an [example](https://github.com/acuminous/yadda/tree/issue-140/examples/issue-140) setting up and running over 2000 steps, but it doesn't reproduce what you're seeing using Yadda without any plugins.

I'll try and make it more like what you're doing with Karma and Mocha.

**Comment by cressie176** [comment]
Just created another branch with a mocha [example](https://github.com/acuminous/yadda/tree/issue-140-mocha/examples/issue-140) but still doesn't reproduce. 

I'm using 
node v0.10.38
yadda v0.11.6 (no significant differences from v0.11.5)
OSX

Are you able to run this example and see if it reproduces in your environment (appreciate not using karma yet)

**Comment by cressie176** [comment]
bump
