### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lolmaus** [acuminous/yadda#142]
Hi!

In my EmberJS project, I would like to split my acceptance tests into scenarios and step implementations. Yadda seems to be a natural choice.

Unfortunately, there's not enough documentation on how to integrate Yadda into testing infrastructures. I'm understanding the [Writing Yadda Tests](https://github.com/acuminous/yadda#writing-yadda-tests) section up to Step 3. But Step 4 "Integrate Yadda with your testing framework" is unexplained magic.

Yadda claims to support a lot of testing environments, but plugins seem to be implemented [only](https://github.com/acuminous/yadda/tree/master/lib/plugins) for Casper and Mocha.

Does this mean that I can use Yadda with QUnit natively? How?

EmberJS test environment is based on QUnit but it has its own async helpers for flow control. It seems that I need to pass those helpers into Yadda step implementations.

**Comment by cressie176** [comment]
Sorry you had trouble finding the examples. Thanks for the PR. It's a good idea to link to the examples folder from the readme, however I preferred the original wording so just made the word "examples" a link.
