### ISSUE TITLE
Use yadda in the browser

### ISSUE THREAD

**Issue by retorquere** [acuminous/yadda#145]
I'm looking to use yadda to test my firefox extension. The tests would run wholly within the browser, executing chrome code. Is it possible to setup yadda and feed it the required feature files entirely from code? The feature files would come from the resource bundle, so my own code would have to load them rather than yadda using a file loader.

**Comment by cressie176** [comment]
Sure. Yadda just takes arrays of strings. See https://github.com/acuminous/yadda/blob/master/test/FunctionalTests.js#L17-L25 and https://github.com/acuminous/yadda/blob/master/examples/qunit/test.html for examples

**Comment by retorquere** [comment]
Cool. Any way to report other than to HTML? I'd kick off the tests deep in the browser and am looking to report the ongoing status in json format over http by a firefox-embedded server. The qunit approach from the second link looks to be the way to go there -- am I correct when I assume that when I use the setup from that second link together with https://github.com/JamesMGreene/qunit-reporter-junit I'd be good to go? That would be awesome.

**Comment by retorquere** [comment]
To be more specific: could I get insight in the testing progress in some way while the tests are running? I'm looking e.g. at http://api.qunitjs.com/category/callbacks/, but I don't know how Yadda interacts with those. I think the qunit-reporter-junit reporter only yields an en-of-all-tests status, and I'd need to be able to track progress.

**Comment by cressie176** [comment]
You can listen for [events](https://github.com/acuminous/yadda#events)

**Comment by retorquere** [comment]
Ah, and the unit example seems to need a `<div id="qunit"></div>` for its output, which I can't offer.

**Comment by cressie176** [comment]
Probably worth a better explanation...

The simplest way to invoke yadda is with an array of strings. Each string is a 'step' and the array is a 'scenario. After the scenario has executed Yadda will return if the step/scenario is sync, or callback if it's async. Scenario and Step events will be emitted, so you can listen for lifecycle events as the scenario executes.

What you do to get the array of strings is up to you. You can parse them from files, or html, from a REST response, etc, etc, etc

**Comment by retorquere** [comment]
Ah, great! I take it the FeatureParser does just that -- parse a text into such an array. From that array, I could glean how many tests will be run, and the scenario and step events would give me fail/succeed status of those.

The remaining detail I could use some help on is on the meaning of https://github.com/acuminous/yadda/blob/master/examples/qunit/test.html#L18 - 24 -- is the `test` function something from qunit?

Apologies for the ream of questions, but I think the way I intend to use yadda is a little different from how it will usually be employed, and the otherwise entirely reasonable assumptions about the environment (be it node or an HTML page) don't hold for me.

**Comment by cressie176** [comment]
Yes the 'test' is function provided by QUnit to create tests. No need to apologise

**Comment by retorquere** [comment]
I appreciate that. I think I have a standalone scenario specced out at https://gist.github.com/anonymous/d4828800a21b3e5d8196. The one thing I still don't fully grasp is how the event handlers can give me progress feedback -- the SCENARIO event triggers on scenario start, and I can use that to track progress in terms of how many scenarios remain to be executed, but how do I glean success/failure? Or should I just wrap each `Yadda.createInstance(library).run(scenario.steps)` in a try-catch block? 

Am I correct in assuming that executing `Yadda.createInstance(library)` in the loop serves to give each scenario a clean start in some way?

**Comment by cressie176** [comment]
Providing your steps are synchronous then wrapping yadda run inside a try catch block will work. If your steps are asynchronous you'll need to pass each step a callback and inspect the error argument. 

The reason for this is that Yadda is really just a library for mapping a string to a function then executing the function using parameters parsed from the string. I've included some plugins and examples showing how it can be incorporated into other test frameworks (e.g. mocha / qunit), but all the truly test specific stuff is done by those libraries.

I haven't developed any firefox extensions but if you can depend on Yadda can you depend on a test framework like [tape](https://www.npmjs.com/package/tape)?

**Comment by retorquere** [comment]
Can you add an example to that gist to show the async case?

The firefox extension environment lives a little between node and a webpage. You can do pretty much everything you could do in node, but there's no `require`, so the environment is very much like a webpage, except you have no HTML DOM to manipulate. So I think I could use tape -- would you recommend I do?

**Comment by retorquere** [comment]
on the EventBus.ON_SCENARIO, can I get the title of the scenario?

**Comment by cressie176** [comment]
Yes See [here](https://github.com/acuminous/yadda/blob/master/lib/Interpreter.js#L56) and [here](https://github.com/acuminous/yadda/blob/master/lib/Interpreter.js#L70)

**Comment by retorquere** [comment]
When I log the value of the event object in the ON_SCENARIO event, I get

    { name: '__ON_SCENARIO__',
      data:
       { scenario:
          [ 'Given 100 green bottles are standing on the wall',
            'when 1 green bottle accidentally falls',
            'then there are 99 green bottles standing on the wall' ],
         ctx: {} } }

The name of the scenario is `A bottle falls from the wall`

**Comment by retorquere** [comment]
Would you in general recommend wrapping yadda inside something like qunit or mocha? Or is "raw yadda"  an equally valid approach?

**Comment by cressie176** [comment]
You're right about the scenario event. Yadda only takes arrays of strings so any feature title or scenario titles don't make it through. The pattern I've followed with most of the examples is to iterate through the features / scenarios and report the titles before invoking yadda. e.g.

```js
var yadda = Yadda.createInstance(library)
for (var f = 0; f < features.length; f++) {
  console.log(features[f].title)
  for (var s = 0; s < features[f].scenarios.length; s++) {
    console.log(features[f].scenarios[s].title)
      yadda.run(features[f].scenarios[s].steps)
  }
}
```
(none of the examples actually look like that but you get the idea).

As to whether I recommend wrapping yadda inside something else - I've never been asked. Typically people have their favourite test runner and they want to keep using it, so the questions are usually how do I integrate Yadda with framework X. I don't have any experience of testing firefox extensions so can't advise.

**Comment by retorquere** [comment]
I'm coming from ruby cucumber, and I'd really rather not layer in any dependency that I don't have to. In the end, I need to be able to 

1. Run a (selective) bunch of scenarios. Yadda does this without needing anything from the outside
2. Run sync tests and async tests. The sync tests are clear to me, but what the setup would be for async tests given the "next" function is not yet clear to me.
3. Follow progress as tests run. For sync tests this is easy; I kick them off myself so I know when they start and which fraction of them is done; if I want some kind of visual tracking I can use STEP or EXECUTE (not sure on what the diff is between those), and catch an error to track failure. For scenarios with async tests (which I'd love to have) this is not yet clear to me
4. Profit.

**Comment by cressie176** [comment]
> The sync tests are clear to me, but what the setup would be for async tests given the "next" function is not yet clear to me.

The 'next' function (often called done or callback or cb), is a function that will be executed on completion of some asynchronous code (e.g. an ajax request). The first argument is typically an error object which is null or undefined if the asynchronous code completed successfully. If the code under test isn't making asynchronous calls there's no need to use it in Yadda.

You can compare the [basic](https://github.com/acuminous/yadda/blob/master/examples/basic/demo.js) and [basic-async](https://github.com/acuminous/yadda/blob/master/examples/basic-async/demo.js) demos to see how you can incorporate async if you need.

>  I can use STEP or EXECUTE (not sure on what the diff is between those)

EXECUTE fires slightly later and dumps out slightly more stuff

> For scenarios with async tests (which I'd love to have) this is not yet clear to me

I'd say avoid async unless you need it (i.e. the code under test is asynchronous) - it will only complicate things

>Profit.

FTW

**Comment by retorquere** [comment]
Trust me, I'd rather do sync, but there's a few spots where code that I depend on is async. The way I work around that is an ugly hack spinning the event loop that Mozilla wants me to stop doing/ The point would then be, if I understand correctly, to call `next()` in the async return callback of the code I'm calling to signal Yadda that the step finished. But how do I pass failure to Yadda (assuming the call to `next()`) signals success? And how would I run two consecutive (not parallel) async tests in that latter sample?

**Comment by retorquere** [comment]
Can a library have a mixture of sync and async step definitions?

**Comment by cressie176** [comment]
> But how do I pass failure to Yadda (assuming the call to next()) signals success?

You either have to ensure your test runner handles errors throw from asynchronous context. In node you can do this with domains. In a browser maybe with a global error handler?

Alternatively you should [pass an error to the callback](https://github.com/acuminous/yadda/blob/master/examples/basic-async/lib/bottles-library.js#L25) and handle it [here](https://github.com/acuminous/yadda/blob/master/examples/basic-async/demo.js#L12).

> How would I run two consecutive (not parallel) async tests in that latter sample?

I'd use [async](https://github.com/caolan/async). If you prefer promises go for something like [bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md) 

> Can library have a mixture of sync and async step definitions?

Yes, but you can't mix them in a scenario.

**Comment by retorquere** [comment]
As Zotero is moving to bluebird anyway I might as well get to grips with that. Thanks, this should be enough to get me going.

**Comment by cressie176** [comment]
OK to close?

**Comment by retorquere** [comment]
Yes, sorry.

**Comment by retorquere** [comment]
Sorry to bother you again, but how would I string together a list of scenario runs with bluebird? The async example is clear, but promises are included in my environment and I'd rather not introduce more new dependencies than needed; mozilla chrome code is a peculiar environment, and many libs need tweaks to be made to work there.

**Comment by cressie176** [comment]
I haven't actually used bluebird (I'm not a fan of promises and do my best to avoid them). However I'd imagine you'd run yadda from inside a ```then``` in a similar way to the [webdriver example](https://github.com/acuminous/yadda/blob/master/examples/mocha-webdriver/test.js).
