### ISSUE TITLE
Error parsing background

### ISSUE THREAD

**Issue by retorquere** [acuminous/yadda#146]
With https://gist.github.com/3e9f6ff73d5caf31acdb, the parser fails with 

    Error: Error parsing line 12, "@test-cluster-0 @131".
    Background requires one or more steps

the background does have a  step though. Commenting out line 4+5 makes the error go away.

**Comment by cressie176** [comment]
Suspect it's a bug. If you insert a blank line it will work.
```
Background:

  When I set preference .citekeyFormat to [auth][year]
``` 
This is probably a left over from an earlier version of Yadda when Scenarios could have descriptions. Please leave open and I'll investigate a bit further

**Comment by cressie176** [comment]
The fix is easy, but want to get some feedback on whether anyone finds background descriptions useful.  I've added the following console.log to the latest version of yadda. 

```
It appears that you are using background descriptions that either span
mutliple lines or begin immediately beneath the 'Background' keyword
We are considering removing this feature. Please update
https://github.com/acuminous/yadda/issues/146 if it is important to you
You can disable this message by setting FeatureParser.silence146 to true
```

If no-ones raised any concerns in the next month I'll bin them.

**Comment by retorquere** [comment]
You mean bin them as in remove the background feature entirely? I don't mind the extra line of whitespace, but to do without background would be a pain.

**Comment by cressie176** [comment]
No, the background feature is staying. Earlier on in Yadda's lifetime I misunderstood a feature request and added descriptions to scenarios.

```
Scenario: This is a title
This is a description
```
The consequence was that you needed to add a blank line before the steps so Yadda could tell the difference between descriptions and step text. It caused no end of problems so I removed it. Looks like I forgot to remove it from Backgrounds

**Comment by samzhao** [comment]
IMHO, background description isn't necessary because the background steps are more or less the descriptions.
