### ISSUE TITLE
support features in cucumber-tck

### ISSUE THREAD

**Issue by AntonioDrusin** [acuminous/yadda#147]
Should yadda become a superset of cucumber or was the intention to implement a slightly different version of gherkin? I was toying with the idea of running the cucumber-tck in yadda. But would like to know what you think of certain differences. For example a feature is required to pass if it has no scenarios. This is not so (intentionally) in yadda.

**Comment by cressie176** [comment]
Hi Antonio,

> Should yadda become a superset of cucumber or was the intention to implement a slightly different version of gherkin?

Cucumber has features that Yadda is not likely to support any time soon so it's unlikely to become a superset. I didn't deliberately make the syntax slightly different - My primary motivation for writing Yadda was that I didn't want to be restricted by Gherkin, so I didn't give it too much thought.

> I was toying with the idea of running the cucumber-tck in yadda. But would like to know what you think of certain differences. For example a feature is required to pass if it has no scenarios. This is not so (intentionally) in yadda.  

I'd be curious to see the failures. When writing Yadda I didn't make deliberate decisions to deviate from cucumber spec, I just did what I thought was sensible at the time. If I've made a bad decision, I'm happy to reverse it. However I wouldn't change Yadda to do what I considered to be the wrong thing, purely for compatibility with Cucumber.

**Comment by AntonioDrusin** [comment]
I started including the cucumber-tck here https://github.com/AntonioDrusin/yadda
I just got as far as doing the core.feature. Maybe implementing the cucumber-tck is not the right thing to do for yadda. It would just become another implementation of cucumber-js. 

Thank you so much for such great work.
