### ISSUE TITLE
@Only annotation breaks when running tests with Jasmine

### ISSUE THREAD

**Issue by samzhao** [acuminous/yadda#154]
Hi,

In case anyone else encountered similar problems with Jasmine, I created this issue to post a workaround and hopefully start some discussions on whether or not to integrate this workaround into Yadda's codebase.

This is the error I got when I tried to use the `@Only` annotation on my Scenarios:

```
TypeError: _it is not a function
at it_sync (/Users/<username>/dev/<project-name>/client/tests/test.js:14266:10 <- webpack:///~/yadda/lib/plugins/mocha/BasePlugin.js:61:0)
```

*Note:* I'm using Webpack and Karma for testing so the `test.js` is the large compiled bundle file, and there's sourcemap set up for webpack to reference the actual file that `test.js` required.

After some digging, I've found the problem is actually [in this line](https://github.com/acuminous/yadda/blob/0b5e28b932eb9e054de501c2ce37e99db3be88dd/lib/plugins/mocha/BasePlugin.js#L68) where

```
if (has_annotation(annotations, 'only')) return container.it.only;
```

the `it.only` is `undefined`.

I don't think Jasmine has an `it.only` method, or maybe it does and just references `iit` internally, but that's what caused the problem.

**Here's my workaround:**

```javascript
if (jasmine.version) { // for v2.x
    // Jasmine 2.x abandoned iit/ddescribe in favor of fit/fdescribe ('f' as in focused)
    global.it.only = fit
    global.describe.only = fdescribe
}
else { // for v1.x
    global.it.only = iit
    global.describe.only = ddescribe
}
```

I don't know Yadda's codebase well enough to suggest a fix in Yadda itself, but I hope this helps someone who got stuck with this error.

**Comment by cressie176** [comment]
Thanks for reporting and posting the workaround. I'll take a look.

**Comment by samzhao** [comment]
No problem. Thanks for the fix!
