### ISSUE TITLE
Issue using Annoated Example Tables

### ISSUE THREAD

**Issue by iamcdonald** [acuminous/yadda#155]
Hi,

I've pasted a dummy feature file I've been trying this out in.
When passing this through the FeatureParser I get
```sh
Text is unexpected at this time
    at parse_line (/Users/wizzart/Documents/nadda/node_modules/yadda/lib/parsers/FeatureParser.js:78:19)
```

I assume I'm doing something wrong I just can't see a difference between my file and the example given in the README.

my feature file 
```
Feature: ACCESS THE INTERWEBZ AND DO A SEARCH
As an internet enabled individual I can
search for at least two things via an
internet search mechanism.

Background:

    Given I visit http://www.duckduckgo.com

Scenario: DuckDuckGo Search for [Type]

    When I type in [Type]
    And I click search
    Then '[Expected]' exists in the page

    Where:
        Type | Expected
        nightwatch | Night Watch
        bower | bower.io
@wip
        nightwatch | Night Watch
@wip
        bower | bower.io
```

Any pointers would be much appreciated.
Thanks,

Iain

**Comment by cressie176** [comment]
Works for me. What version of yadda are you using (should be 0.13.1)

**Comment by cressie176** [comment]
FYI https://github.com/acuminous/yadda/tree/issue-155/examples/issue-155

**Comment by iamcdonald** [comment]
Hi, 
sorry, my bad. 
I thought I'd upped to the most recent version (0.13.1) but apparently not.
Moving up fixed my problem.
Thanks.
