### ISSUE TITLE
Running single feature more than once

### ISSUE THREAD

**Issue by riaan53** [acuminous/yadda#156]
Hi,

If I tag a specific feature like this:

```gherkin
@browser=chrome,safari
Feature: Mocha Asynchronous Example

  Scenario: A bottle falls from the wall

    Given 100 green bottles are standing on the wall
    when 1 green bottle accidentally falls
    then there are 99 green bottles standing on the wall
```

I want to run the same feature over the two browsers in mocha in series and have the option to run it concurrently.

What would be the best way to approach this? 

btw great work so far with yadda!

Thanks,

Regards,
Riaan

**Comment by cressie176** [comment]
I'd start by looking at [moonraker](https://github.com/LateRoomsGroup/moonraker) and [cucumber-boilerplate](https://github.com/webdriverio/cucumber-boilerplate), both of which use Yadda under the hood. There's an issue discussing how to do just this with moonraker [here](https://github.com/LateRoomsGroup/moonraker/issues/27). 

If I wanted to do something similar with raw Yadda then I would probably take a similar approach - modify test.js to check for a browser cli argument, and only execute the features tagged with that browser.

Control the parallelism by running invoking the tests sequentially or concurrently.

**Comment by riaan53** [comment]
Ok cool will try it out!

Thanks.

Regards,
Riaan
