### ISSUE TITLE
Are WebdriverJS and CasperJS test frameworks?

### ISSUE THREAD

**Issue by dandv** [acuminous/yadda#163]
> Yadda brings true BDD to JavaScript test frameworks such as Jasmine, Mocha, QUnit, Nodeunit, WebDriverJs and CasperJS.

**Comment by cressie176** [comment]
I suppose "browser automation tools" may be more accurate, however...

> CasperJS is an open source navigation scripting & testing utility written in Javascript for the PhantomJS WebKit headless browser and SlimerJS (Gecko)

and webdriverjs doesn't look like much of anything anymore...

> DEPRECATED
Project is now called WebdriverIO and has moved to webdriverio/webdriverio 

Will update the docs to reflect next time I do a release

**Comment by dandv** [comment]
> and webdriverjs doesn't look like much of anything anymore...

The author of WebdriverIO [likes Yadda](https://gitter.im/webdriverio/webdriverio?at=55c375262c1b3bec3198ec52) and has put together a BDD boilerplate using Yadda:
https://github.com/webdriverio/cucumber-boilerplate.

**Comment by cressie176** [comment]
I also like the look of cucumber-boilerplate. Usually recommend that or http://engineering.laterooms.com/moonraker-test-framework/ when people ask what they should use for functional web tests.

**Comment by cressie176** [comment]
Fixed in the latest github readme. Forgot to update before releasing 0.15.3 though. Doh!
