### ISSUE TITLE
Why is your bower file not at 0.15.2?

### ISSUE THREAD

**Issue by remkoboschker** [acuminous/yadda#166]

**Comment by cressie176** [comment]
Thanks for the nudge. Will update

**Comment by remkoboschker** [comment]
Thank you very much for Yadda. 

Would you mind adding a amd version in the dist? I'm writing a ember-cli addon that uses yadda to run acceptance tests written in Gherkin against an ember app. It is easier to include amd modules in the current ember-cli resolver / loader. 

I have now solved this by simply adding 

````
define('yadda',
  [],
  function() {
    return require('api');
  })
````
to the bottom of the dist file.

**Comment by remkoboschker** [comment]
@cressie176 I managed to load the lib in a different way. https://github.com/curit/ember-cli-yadda/blob/master/test-support/helpers/yadda.js

**Comment by cressie176** [comment]
OK. Happy to add an amd module too. Working on a new library atm so taking a bit longer to get around to the yadda stuff.

**Comment by remkoboschker** [comment]
Great, thanks.

**Comment by cressie176** [comment]
I've updated the bowser file to 0.15.2. I haven't used bowser for so long that I'm not very familiar with it. Any chance you can test it out?

**Comment by remkoboschker** [comment]
I'lll have a look, thanks

**Comment by remkoboschker** [comment]
You need to tag the 0.15.2 release for bower to pick it up.

**Comment by cressie176** [comment]
Thanks. Was tagged, but I'd forgotten to push. Pushed now.

**Comment by remkoboschker** [comment]
works a treat, thanks
