### ISSUE TITLE
Parser failure when providing additional Feature: description

### ISSUE THREAD

**Issue by commandline** [acuminous/yadda#169]
This works:
```
Feature: My awesome product feature
```
This fails parsing on the second line:
```
Feature: My awesome product feature
    As a user I want to use awesome feature
    So that I can be really happy
```
I am unsure if this is intentional, feel free to comment and close if it is. If not, we are also having problems because the parse exception is hard to dig out with the way we integrate yadda with Mocha/Karma.

**Comment by cressie176** [comment]
I suspect the parser is interpreting the ```As a user``` and ```So that I``` lines as part of the feature description (multiline feature descriptions are supported). 
```
Feature: My awesome product feature
    As a user I want to use awesome feature
    So that I can be really happy
```
Should be either...
```
Feature: My awesome product feature

Scenario:
    As a user I want to use awesome feature
    So that I can be really happy
```
Or just
```
Scenario: My awesome product feature
    As a user I want to use awesome feature
    So that I can be really happy
```

Let me know if that works.

**Comment by commandline** [comment]
In the actual (private) Gherkin source where I saw this, moving the lines to a scenario would not actually be accurate. The additional lines are definitely part of making clear the user value of the whole feature, as opposed to any particulars covered by a scenario. If multiline feature descriptions are supposed to be supported, I'll posit this is then a bug, we are definitely seeing a parse error arising from the first non-empty line after the one with "Feature:" and can only get around it by commenting (#) those additional lines. I'll offer to come up with something that demonstrates this more clearly but am already well overdue on my offer to do so with another issue, so no promises on timeliness. :/ Regardless, it is minor since the workaround is simple.

**Comment by cressie176** [comment]
>  The additional lines are definitely part of making clear the user value of the whole feature

Sorry I misunderstood - I thought they were steps. Having a look now

**Comment by cressie176** [comment]
https://github.com/acuminous/yadda/blob/issue-169/examples/mocha-async/features/bottles.feature works fine for me. 

- What version of yadda are you using? 
- Can you paste the rest of your feature file (feel free to anonymise)?

**Comment by commandline** [comment]
0.15.2 and I wonder if it is a blank line after the line with the Feature: label?
```
Feature:

	As a user
	I should see uncustomized content warning
	When I do the thing with such content

Background:

	Given the user has opened a new something in app

Scenario: Verify the presence of uncustomized content warning on doing things

	Given the user has added the uncustomized-title thing
	When they do the thing to the thing
	Then they should see a warning about the uncustomized content
```
If I comment the lines between the Feature: Line and the Background: line, it works. I know at one point, with an older version, we were running into a problem with blank lines and Background: labels. Wonder if it is something to do with backgrounds since we use those pretty comprehensively in our suite.

**Comment by commandline** [comment]
And checking on that Feature/Background question, I found a feature file in our suite that fails with this error that does *not* have a Background: label between Feature: and the first Scenario: label.

**Comment by cressie176** [comment]
```
Feature:

    As a user
    I should see uncustomized content warning
    When I do the thing with such content

Background:
```
Will result in a parse error since the feature description is terminated by a blank line.

```
Feature:
    As a user
    I should see uncustomized content warning
    When I do the thing with such content

Background:
```
would be OK

**Comment by commandline** [comment]
Ah ha! OK, so it isn't a bug, it is a misunderstanding of how to correctly use the Feature label on our part--thanks! I will make sure to spread this understanding and enhance our error handling around this particular parse failure to guide our folks towards avoiding an inadvertent termination of the Feature description. Feel free to close this issue and thanks for taking the time to clarify.
