### ISSUE TITLE
Seg fault in nodejs

### ISSUE THREAD

**Issue by commandline** [acuminous/yadda#170]
You ready for a fun one? We are pulling yadda into our second project. The first project used in with Karma and Mocha for in browser tests. It works well and we are growing our suite rapidly.

I just did the early leg work to start building acceptance tests for the companion node project, using just mocha along with yadda and webdriverio. Our first scenario and feature worked beautifully so I gave the green light to our QE team to start expanding on my initial work.

Our second feature and scenario generates a segfault. Every time. One of our QE folks thinks he has narrowed it down to the Levenshtein distance calculation in the scoring engine.

https://github.com/acuminous/yadda/blob/master/lib/LevenshteinDistanceScore.js#L61

I suspect a resource issue based on our nodejs config, maybe a stack size limit per process or it is possible that long lines of text in the step descriptions is pushing this cartesian product beyond what nodejs can easily handle.

**Comment by commandline** [comment]
I will work on the environment side, to see if there is something I can tweak with nodejs to alleviate this. In the meantime, none of our suite relies on the fuzzy matching so if there is a way to disable the distance calculation or one can simply be added, that would also give us a workaround for node based tests.

**Comment by commandline** [comment]
These may be worth considering if an approximate is acceptable in place of an accurate distance calculation.

http://stackoverflow.com/a/4057585

**Comment by cressie176** [comment]
It's a known bug with node. Arround 0.10.35 I think. I can dig out the
their bug number in a bit. If you update you should be fine (unless they
have regressed)

On Friday, 4 September 2015, Thomas Gideon <notifications@github.com> wrote:

> I will work on the environment side, to see if there is something I can
> tweak with nodejs to alleviate this. In the meantime, none of our suite
> relies on the fuzzy matching so if there is a way to disable the distance
> calculation or one can simply be added, that would also give us a
> workaround for node based tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acuminous/yadda/issues/170#issuecomment-137820514>.
>


-- 
http://peaceoneday.org/

**Comment by commandline** [comment]
Ah, yeah, we are stuck on 0.10.3x--let me see what the latest in that series is and if we can reproduce with that. That matches what digging I have been doing since opening this. I'll confirm in the next little bit so you can close this--thanks for the fast reply!

**Comment by cressie176** [comment]
Was fixed in the next patch release of node so if you are worried about
upgrading you only need to move up one version.

Worth doing as it doesn't affect just Yadda but any potentially any code
with nested for loops (as in levenstein distance code)

On Friday, 4 September 2015, Thomas Gideon <notifications@github.com> wrote:

> Ah, yeah, we are stuck on 0.10.3x--let me see what the latest in that
> series is and if we can reproduce with that. That matches what digging I
> have been doing since opening this. I'll confirm in the next little bit so
> you can close this--thanks for the fast reply!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acuminous/yadda/issues/170#issuecomment-137826349>.
>


-- 
http://peaceoneday.org/

**Comment by commandline** [comment]
Yeah, this is definitely the issue. Our nodenv was set to just v0.10, which must pin to something stupid like v0.10.0. I changed that explicitly to v0.10.38 which I think is the current for that release and I am on my 3rd run with no problems. Feel free to close and thanks for both your help and your patience.

**Comment by cressie176** [comment]
[here](https://github.com/nodejs/node-v0.x-archive/issues/8208) is the node defect. It affected 0.10.31 not 0.10.35 as I previously stated.
