### ISSUE TITLE
Segmentation fault in LevenshtienDistanceCore.js

### ISSUE THREAD

**Issue by puttagunta** [acuminous/yadda#171]
Segmentation fault is happening in the following piece of code

```
for (var j = 0; j < s2.length; j++) {
            for (var i = 0; i < s1.length; i++) {
                if (s1[i] == s2[j]) {
                    distance_table[i+1][j+1] = distance_table[i][j];
                } else {
                    var deletion = distance_table[i][j+1] + 1;
                    var insertion = distance_table[i+1][j] + 1;
                    var substitution = distance_table[i][j] + 1;
                    distance_table[i+1][j+1] = Math.min(substitution, deletion, insertion);
                }
            }
        }
```

Replacing that with, s1.match(/([a-zA-Z]+\s+)/i)[0].length solved the problem. But, I'm not sure if it can replace Levenshtien algorithm. 
Node version on which this is tested is v0.10.x on OS X Yosemite.

**Comment by cressie176** [comment]
Thanks for reporting. This is caused by a bug in node 0.10.31. Upgrading node to any more recent version will fix it. See [here](https://github.com/nodejs/node-v0.x-archive/issues/8208) for details of the bug.
