### ISSUE TITLE
console enhance  (suggestion)

### ISSUE THREAD

**Issue by ami44** [acuminous/yadda#175]
Hello, I test the new table functionality. very great !
I have a suggestion: can you improve the console.

Example, today I have:

```
     update / D: 0:
       √ When json {
   "Days": [
   ],
   "errors": null,
   "status": "OK"
}
       √ Then get {
     "events": {}
     "days": {}
}
       √ and next ...
```
I would rather have

```
     update / D: 0:
       √ When json {
       |    "Days": [
       |    ],
       |   "errors": null,
       |   "status": "OK"
       | }
       √ Then get {
       |   "events": {}
       |   "days": {}
       | }
       √ and next ...
```

or other indentation
Thanks
Ami44

**Comment by cressie176** [comment]
I made a change in the latest version of yadda so the multiline steps at least start on a new line. Not sure if you're using that version.

Not sure what else is feasible - the steps are still just strings, which get passed to mocha's describe and it methods. It might be possible to write a mocha reporter to display the output differently. I'm not likely to have any time to look into this though.

**Comment by cressie176** [comment]
Just took a look at the data-table example. While not indented the output looks better for the first two examples

```
  List
    List
      ✓ Given a list of integers
1000
2022
9405
      ✓ Then the total should be 12427
    Simple Table
      ✓ Given a table of data
left | right
1    | 3
2    | 4
      ✓ Then the left total should be 3
      ✓ And the right total should be 7
```

The third example for multiline data-tables (not shown) isn't working in scenarios yet. Still working on that. They work in examples though.

**Comment by cressie176** [comment]
If you upgrade to the latest version of Yadda you may find your scenarios stop working. Unfortunately you need to use a special character in your steps for multiline steps, e.g.

```
Scenario: List

    Given a list of integers
    ----
    1000
    2022
    9405
    ----

    Then the total should be 12427
```

```
    var dictionary = new Dictionary()
        .define('list', /([^\u0000]*)/, Yadda.converters.list)
        .define('table', /([^\u0000]*)/, Yadda.converters.table);

    var library = English.library(dictionary).given("a list of integers\n$list", function(list) {
        list_total = 0;
        for (var i = 0; i < list.length; i++) {
            list_total += parseInt(list[i]);
        }
    })
```

**Comment by ami44** [comment]
Thanks for your help
Ami44
