### ISSUE TITLE
Where are converters assigned to regular expressions?

### ISSUE THREAD

**Issue by nareshbhatia** [acuminous/yadda#176]
I just went through the [tutorial](https://acuminous.gitbooks.io/yadda-user-guide/content/en/getting-started/tutorial.html). I am really liking Yadda - great work!

One thing I could not understand is how does the following step definition work:

    .given("$NUM green bottles are standing on the wall", function(number, next) {
    }

- Where is $NUM assigned to a number converter? Is it part of the English dictionary?
- I read that Yadda provides converters for integers, floats and dates. I assume that $NUM is associated with the integer converter. What are the equivalents for floats and dates?
- What's the best way to parse a simple name? For example, I need to create a feature step like this:

        When I create an account called "Bank of America Checking"

How do I parse the name "Bank of America Checking"? Just use a RE like `"([^"]*)"` or is there a better way in Yadda?

**Comment by cressie176** [comment]
Re: $NUM

Any word you prefix with a $ gets replaced with (.+) by default. The dictionary and the  converters are optional, however in the $NUM example, not using them means you'll be getting a string "1234" rather than an integer.

Re: Bank of America
```
.when('I create an account called "$ACCOUNT", function(accountName, next) {
}
```
is all you'd have to do

**Comment by nareshbhatia** [comment]
Awesome! Thanks for the quick response.

Unless it is documented somewhere, I missed the fact that $ gets replaced with (.+). The closest I could find is on [Step Libraries](https://acuminous.gitbooks.io/yadda-user-guide/content/en/usage/step-libraries.html) page where it states that "Use terms to make your steps more friendly". May be worth making it more explicit.
