### ISSUE TITLE
Where to put database hooks?

### ISSUE THREAD

**Issue by nareshbhatia** [acuminous/yadda#177]
I need to initialize a database connection before any tests run, then wipe out all database data before any scenario runs and finally close the database connection when all tests are done. With raw mocha, I generally do this using hooks (see example [here](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/mocha-mocha-supertest/test/specs/hooks.spec.js)). How do I do the same with yadda?

**Comment by cressie176** [comment]
If you're using the mocha plugin, you can use before, beforeEach, afterEach and after in the normal way

**Comment by nareshbhatia** [comment]
Awesome! That works. So each mocha test corresponds to a scenario?

**Comment by cressie176** [comment]
Depends whether you use the scenario level plugin or step level plugin. With the scenario level plugin ```describe``` is called per feature, and ```it``` called per scenario. With the step level plugin ```describe``` is called per feature and scenario, ```it``` is called per step.

**Comment by nareshbhatia** [comment]
I see. So when I earlier said it is working, it was really not working. I was using the StepLevelPlugin (from the basic Yadda example) and it was clearing the database on every step. So the final "Then" started to fail. Looking into the Scenario level plugin now. Just out of curiosity, what are the pros and cons of StepLevelPlugin vs. ScenarioLevelPlugin?

**Comment by cressie176** [comment]
When you use the StepLevelPlugin, each step in your scenario is executed inside a mocha ```it``` call. i.e. each step is a separate mocha test. This is generally better for output, because you see all the steps execute. With the ScenarioLevelPlugin you only see the scenario title in the mocha output.

To setup / teardown a database use mocha's ```before``` and ```after``` functions, however you need to take care where you position them in your test. Make sure they're outside any calls to ```feature``` and they should execute before and after the yadda test suite.

**Comment by nareshbhatia** [comment]
@cressie176 - I am not able to make the ScenarioLevelPlugin work. Can you please help? I have a very simple scenario checked in [here](https://github.com/archfirst/acceptance-testing-best-practices/tree/master/mocha-yadda-supertest). In [test.js](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/mocha-yadda-supertest/test/test.js) I have both two version of mocha integration, one with StepLevelPlugin and another with ScenarioLevelPlugin. The database hooks are defined in [hooks.js](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/mocha-yadda-supertest/test/hooks.js).

The StepLevelPlugin correctly steps through the hooks, but the test fails because it is wiping out the database after each step (step 2 is expecting the data saved by step 1). So this issue is perfectly explainable.

The ScenarioLevelPlugin tries to solve the problem by cleaning the database before each scenario but not between steps. However in this case the test times out before reaching the first step in the scenario. Here's the console log:

    mocha:before - create database connection
      Accounts
    mocha:beforeEach - clean up database tables
        1) Account Creation
    mocha:afterEach - do nothing
    
    mocha:after - close database connection

      0 passing (2s)
      1 failing

      1) Accounts Account Creation:
         Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by ami44** [comment]
maybe use mocha with option ``--no-timeouts`` 
example : ``mocha --no-timeouts --reporter spec test/test.js``
Ami44

**Comment by cressie176** [comment]
I think there may be an issue with the ScenarioLevelPlugin. Will investigate, however you should be able to use the step level plugin to setup / teardown your database before the features run. This is nothing to do with Yadda - it's just normal mocha behaviour. Maybe the issue is that your before and after aren't async?

Working example [here](https://github.com/acuminous/yadda/commit/0058cfcdc5de34f83507156a8e340f4f4544abae)

**Comment by cressie176** [comment]
ScenarioLevelPlugin bug fixed in 0.15.5

**Comment by nareshbhatia** [comment]
@cressie176, thanks. 0.15.5 resolves my issue.

However, I don't understand your comment about being able to use step level plugin. The issue is that I want to retain the data in the database between steps, but clear it out between scenarios. WIth your example, this is what will happen.

```
before:
    initialize database and create a connection
beforeEach:
    clear database
step 1:
    use database connection to create an account
    save the created account's id in scenario state
beforeEach:
    clear database
step 2:
    use the saved account id to get the account back
    oops, account will be not found because database has been cleared!

```

**Comment by cressie176** [comment]
Forgetting about Yadda, just expressing as a mocha test, I believe the following would initialise the database connection before the first describe, and clear the database before running the tests in each scenario. 
```
before(function(done) {
    // initialize database and create a connection
})
after(function(done) {
   // close database connection
})
describe('Feature', function() {
   describe('Scenario 1', function() {
      before(function(done) {
         // clear database
      })
      it('Step 1', function() {
      ])
      it('Step 2', function() {
      ])
      it('Step 3', function() {
      })
   })
   describe('Scenario 2', function() {
      before(function(done) {
         // clear database
      })
      it('Step 1', function() {
      ])
      it('Step 2', function() {
      ])
      it('Step 3', function() {
      })
   })

});
```
With Yadda this would be
```
new Yadda.FeatureFileSearch('features').each(function(file) {

    before(function(done) {
       // initialize database and create a connection
    })
    after(function(done) {
      // close database connection
    })

    featureFile(file, function(feature) {

        var library = require('./bottles-library');
        var yadda = Yadda.createInstance(library);

        scenarios(feature.scenarios, function(scenario) {

            before(function(done) {
                // clear database
            })

            steps(scenario.steps, function(step, done) {
                yadda.run(step, done);
            })
        })
    })
})
```

**Comment by nareshbhatia** [comment]
@cressie176, thanks for clarifying. I got confused between Mocha *Root-Level Hooks* vs. the before/after hooks in the Yadda test.js file. I was using *Root-Level Hooks* in a hooks.js file. These Mocha hooks were being triggered for every *it*! As soon as I switched to hooks inside my test.js, the StepLevelPlugin started working perfectly.

Thanks for answering my newbie questions patiently.

**Comment by cressie176** [comment]
Very welcome. Thanks for spotting the bug in ScenarioLevelPlugin

**Comment by nareshbhatia** [comment]
@cressie176, I am reopening this issue because I noticed a problem with releasing database connections. As discussed above, I am using the `StepLevelPlugin` with `before` and `after` hooks to initialize and release database connections wrapping every feature (see the actual code [here](https://github.com/archfirst/acceptance-testing-best-practices/blob/master/mocha-yadda-supertest/test/test.js)). Unfortunately, the way it is actually working with multiple feature files (4 in my case) is that I am seeing 4 `initDb` calls simultaneously, then all the tests run, and finally 4 `releaseDb` calls. See below:

```
initDb
initDb
initDb
initDb
  Accounts
  ...
  Categories
  ...
  Reporting
  ...
  Transactions
  ...
releaseDb
releaseDb
releaseDb
releaseDb
```

This is really confusing the database, as it is the same connection that we are dealing with. Ideally I would like to call `initDb` only once, then execute all feature files and finally call `releaseDb`:

```
initDb
  Accounts
  ...
  Categories
  ...
  Reporting
  ...
  Transactions
  ...
releaseDb
```

Can you please suggest how I could achieve this?

**Comment by xeladotbe** [comment]
Hi @nareshbhatia,

did you try to put your before and after hook outside the function? 

inside function: (your code)

```
new Yadda.FeatureFileSearch('./test/features').each(function(file) {

    // Establish before and after hooks for the test suite
    before(initDb);
    after(releaseDb);
```

outside function: (suggestion)

```
// Establish before and after hooks for the test suite
before(initDb);
after(releaseDb);

new Yadda.FeatureFileSearch('./test/features').each(function(file) {
```

**Comment by nareshbhatia** [comment]
Thanks, @xeladotbe. That fixes the issue. I am surprised that calling the same mocha function from different locations changes its behavior. Does mocha understand the context in which the function is being called?
