### ISSUE TITLE
Slightly modified mocha-multi-library is not working for me

### ISSUE THREAD

**Issue by nareshbhatia** [acuminous/yadda#178]
While Yadda's mocha-multi-library example is working for me out-of-the-box, my version (with a slightly difference directory structure) is not working. Note that my features and steps are in different locations, but otherwise the code is the exact copy of the mocha-multi-library example:

```
var Yadda = require('yadda');
Yadda.plugins.mocha.StepLevelPlugin.init();

new Yadda.FeatureFileSearch('./test/features').each(function(file) {

    featureFile(file, function(feature) {

        var libraries = require_feature_libraries(feature);
        var yadda = Yadda.createInstance(libraries);

        scenarios(feature.scenarios, function(scenario) {
            steps(scenario.steps, function(step, done) {
                yadda.run(step, done);
            });
        });
    });
});

function require_feature_libraries(feature) {
    console.log(feature.annotations);
    return feature.annotations.libraries.split(', ').reduce(require_library, []);
}

function require_library(libraries, library) {
    return libraries.concat(require('./test/steps/' + library + '-steps'));
}
```

When it hits the `console.log()` inside `require_feature_libraries`, it prints `{}` - there is no `libraries` property in `feature.annotations`. In your example, the same `console.log()` prints: `{ libraries: 'bottle, common' }`. I am trying to figure out where the `libraries` property is being dropped or never initialized.

**Comment by cressie176** [comment]
Can you paste your feature with the annotations?, e.g.

```
@libraries=foo
Feature: My amazing feature
...
```

**Comment by nareshbhatia** [comment]
That did it. I just missed the fact that you had annotations on the features. Now I understand the real meaning of the comment on the top of test.js!

Thanks so much!
