### ISSUE TITLE
Yadda tables require a top and bottom border

### ISSUE THREAD

**Issue by nareshbhatia** [acuminous/yadda#179]
Yadda parser gives errors if tables do not have top or bottom borders. For example, this does not work:

```
When I create a transaction with the following properties
    | date       | payee               | memo | amount | account     | category         |
    | 2015-02-01 | Chevron Gas Station | Gas  | -30.00 | Amazon VISA | Auto & Transport |
```

This is contrary to the [table documentation](https://acuminous.gitbooks.io/yadda-user-guide/content/en/feature-specs/example-tables.html) that says "The outer borders are optional". I am perfectly ok with providing borders, in which case the docs should be corrected.

**Comment by cressie176** [comment]
That's a multiline step rather than a multiline example. See https://acuminous.gitbooks.io/yadda-user-guide/content/en/feature-specs/steps.html

**Comment by nareshbhatia** [comment]
Sorry @cressie176, I am confused. I don't understand what "That's" refers to in your response. To clarify my question, I am trying to create a table with multiple rows. The following table, with top and bottom borders, works just fine - I get two rows using the table converter:

```
Given the following transactions
    ----------------------------------------------------------------------------
    | date       | payee         | memo  | amount | account | category         |
    | 2015-01-01 | Gas Station   | Gas   | -10.00 | Cash    | Auto & Transport |
    | 2015-01-02 | Grocery Store | Food  | -20.00 | Credit  | Food & Dining    |
    ----------------------------------------------------------------------------
```

The following table, without top and bottom borders, does not work:

```
Given the following transactions
    | date       | payee         | memo  | amount | account | category         |
    | 2015-01-01 | Gas Station   | Gas   | -10.00 | Cash    | Auto & Transport |
    | 2015-01-02 | Grocery Store | Food  | -20.00 | Credit  | Food & Dining    |
```

Is this the intended behavior, i.e. are tables required to have top and bottom borders?

**Comment by cressie176** [comment]
The text you pasted isn't a multiline example, it's a multiline step. To clarify...

```
Feature: Multiline Examples Table

Scenario: [case] Scenario

    Given I need to transpile [case]
    When EcmaScript6=[EcmaScript6]
    Then EcmaScript5=[EcmaScript5]

Examples:
  case             | EcmaScript6              | EcmaScript5
  -----------------|--------------------------|-------------------------------
  arrow function   | var r=arr.map((x)=>x*x); | "use strict";
                   |                          |
                   |                          | var r = arr.map(function (x) {
                   |                          |   return x * x;
                   |                          | });
  -----------------|--------------------------|-------------------------------
  template strings | var s=`x=${x}            | "use strict";
                   | y=${y}`;                 |
                   |                          | var s = "x=" + x + "\ny=" + y;
```
is a multiline example. It doesn't require the top and bottom borders. The following is a multiline step (which you can automatically parse into a table). It does need top and bottom borders.


```
When I create a transaction with the following properties
    | date       | payee               | memo | amount | account     | category         |
    | 2015-02-01 | Chevron Gas Station | Gas  | -30.00 | Amazon VISA | Auto & Transport |
```
FYI I'm not ignoring your other issue about example tables, but it looks a bit more in depth and I have some day job stuff to get through.

**Comment by nareshbhatia** [comment]
Got it now. Thanks for a detailed explanation.

No worries about the other issue. I have worked around it for the meanwhile.
