### ISSUE TITLE
Converter error

### ISSUE THREAD

**Issue by kaasbaardje** [acuminous/yadda#182]
Hi,
first thanks for yadda. It's great.
I wrote a [package](https://github.com/kaasbaardje/gherkin-karma-example) that tries to combine gherkin, mocha and karma in one process chain.
Unfortunately i get a "converter" error log as i try to execute yadda from all versions greater than 0.14.0 by passing through a feature file context variable.
Example:
I want "Henk" as a parameter of my yadda step library function.
feature file:
```
Given I am a registered user "Henk"
```
JavaScript file:
```
yaddaStepLibrary.given(/I am a registered user "$Henk"/, function(input1, done) {
    done();
});
```
TypeError:
![yadda error](https://cloud.githubusercontent.com/assets/13536068/11210163/4f893fac-8d26-11e5-92e5-43c0c27b12f2.PNG)

Since Browserify does not support fs functions your FeatureFileSearch function does not work as well. I know this has been already discussed.. As a result i wrote my own workaround. Maybe it has something to do with it.
**test.spec.js:**
```
module.exports = (function() {
    'use strict';

    var $ = require('jquery'),
        Yadda = require('yadda'),
        yaddaStepLibs = require('./features/step_definitions/*steps.js', {
            mode: 'list'
        }),
        FeatureParser = Yadda.parsers.FeatureParser,
        English = Yadda.localisation.English,
        featureParser = new FeatureParser(English),
        featurePath,
        featureFile,
        feature,
        stepLib;

    /*each step is executed within it's own mocha 'it' function*/
    Yadda.plugins.mocha.StepLevelPlugin.init();

    yaddaStepLibs.map(function(lib) {
        stepLib = lib.module.yaddaStepLibrary;
        featurePath = lib.module.featureBaseName;
        featurePath = "base/test/features/" + featurePath;
        featureFile = $.ajax({
            url: featurePath,
            async: false
        }).responseText;

        runYaddaStepLibrary(featureFile, stepLib);
    });

    function runYaddaStepLibrary(featureFile, yaddaStepLibrary) {
        var yaddaInterpreter = Yadda.createInstance(yaddaStepLibrary);
        feature = featureParser.parse(featureFile);

        scenarios(feature.scenarios, function(scenario) {
            steps(scenario.steps, function(step, done) {
                yaddaInterpreter.run(step, {}, done);
            });
        });
    }
}());
```
**Abstract of example-step.js:**
```
var Yadda = require('yadda'),
	English = Yadda.localisation.English,
	dictionary = new Yadda.Dictionary()
		.define('number', /(d+)/),
	yaddaStepLibrary = English.library(dictionary);

// Given I am a registered user "Max"
yaddaStepLibrary.given(/I am a registered user "$Max"/, function(input1, done) {
    done();
});
```
I don't know if it's just a bug or something i forgott to arrange in code...

Greetings
Max

**Comment by cressie176** [comment]
Suspect it's caused by a combination of [this](https://github.com/ariya/phantomjs/issues/10522) and [this](https://github.com/acuminous/yadda/blame/master/lib/Macro.js#L67). Basically phantom is built on a really really old version of Safari that doesn't have the 'bind' method. You can fix by applying a polyfil https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind. I'll also look into an alternative as it's currently the only place I use bind.

**Comment by cressie176** [comment]
I've replaced the use of bind in 0.16.1. Can you update yadda and see if it fixes the issue?

**Comment by kaasbaardje** [comment]
it worked!!
Woohoo ! Thanks again. :-)

**Comment by kaasbaardje** [comment]
Do you think it would be a good idea to do a pullrequest of my package to your examples?

**Comment by cressie176** [comment]
Thanks for the offer, but I'm shying away from this. The trouble is once I accept a PR for more examples, I need to be able to support them. I haven't got much experience with karma etc.

My preferred option is to update the github with a link to the project. How does that sound?

**Comment by kaasbaardje** [comment]
Sounds good as well. By the way...
I'm using Windows as main OS. If i want to execute your [protractor](https://github.com/acuminous/yadda/tree/master/examples/protractor) example i doesnt work. It only works if i execute the .bat files by my self. i think there's something wrong with the path specification.
I wrote a start.js as a result of this. It uses Promises, only needs one console and doesn't require .bat files. I didn't checked yet if it works in Linux as well.
The only issue is that the cli output is not colored anymore after i updated mocha to the current version. Having solved the problem i would offer you a pull request for this case as well :-)

```
'use strict';

var spawn = require('spawn-cmd').spawn,
    kill = require('tree-kill'),
    pckArgs = require('minimist')(process.argv.slice(2)),
    nodeArgs = process.argv.slice(2),
    isServerlog = pckArgs.serverlog || nodeArgs[0] === "-" ? true : false;

new Promise(function(resolve, reject) {
    var webdriverUpdate = spawn('webdriver-manager', ['update']),
        processes = {
            webdriverUpdate: webdriverUpdate
        };
    registerOnStdOut(webdriverUpdate);

    webdriverUpdate.on('close', function(code) {
        resolve(processes);
    });
}).then(function(processes) {
    return new Promise(function(resolve, reject) {
        var webdriverStart = spawn('webdriver-manager', ['start']);
        processes.webdriverStart = webdriverStart;
        registerOnStdOut(webdriverStart);
        webdriverStart.stdout.on('data', function(data) {
            resolve(processes);
        });
    });
}).then(function(processes) {
    var protractorStart = spawn('protractor', ['conf.js']),
        webdriverErrorLog = "";

    processes.protractorStart = protractorStart;
    registerOnStdOut(protractorStart);
    protractorStart.on('close', function(code) {
        kill(processes.webdriverStart.pid);
        console.log("terminated selenium server");
        if (isServerlog) {
            console.log(webdriverErrorLog);
        }
    });

    if (isServerlog) {
        processes.webdriverStart.stderr.on('data', function(data) {
            webdriverErrorLog += data.toString().trim() + '\n';
        });
    }
}).catch(function(err) {
    console.log("ERROR");
    console.log(err);
});

function registerOnStdOut(process) {
    process.stdout.on('data', function(data) {
        logStringData(data);
    });
}

var logStringData = function logStringData() {
    var logdata = "";
    return function logStringData(data) {
        logdata = data.toString().trim();
        if (logdata) {
            console.log(logdata);
        }
    }
}();
```

**Comment by kaasbaardje** [comment]
Since the issue is resolved i will close it now. Thanks again. I've updated my [yadda-karma example](https://www.npmjs.com/package/gherkin-karma-example). It contains a [gherkin to yadda parser](https://github.com/kaasbaardje/gherkin-yadda). As my example shows another good reason to use yadda i think your idea of linking it in your github repo is good.
Greetings

**Comment by cressie176** [comment]
Thanks. I'll add your project to yadda gitbook next time I'm working on it.
