### ISSUE TITLE
False positives with `mocha.StepLevelPlugin`

### ISSUE THREAD

**Issue by kaasbaardje** [acuminous/yadda#183]
Hi,
if i'm using version 0.14.0 and i get the same bug as mentioned in issue #120.
If the first tests fails the following tests are completed even i there have to fail.

Greetings
Max

**Comment by cressie176** [comment]
Can you try with the latest version of mocha?

**Comment by cressie176** [comment]
It's a while since I looked at this but I suspect jasmine doesn't provide the option to programmatically skip tests. This was only added relatively recently in mocha which is why you needed to upgrade for your other package.

**Comment by cressie176** [comment]
Any luck?

**Comment by kaasbaardje** [comment]
Hi,
sorry for the late response... family, moving to another country stuff...
Unfortunately i had no luck.

Actually... the behavior changed a little bit:
The test results are always true...
One example:
<pre><code>When I search for max
then the title is foo - Recherche Google
</code></pre>

The test result of this must be wrong, since the title should be
`max -  Recherche Google`
and not
`foo -  Recherche Google`.
I picked this from your yadda - protractor example.

Greetings
Max

**Comment by cressie176** [comment]
I got the same. The protractor example was a contribution - I ran it and it passed. I never thought to check whether it would fail though. I've remove it as webdriverjs is deprecated and I'm not familiar with protractor.

**Comment by kaasbaardje** [comment]
Thanks for your quick response. Maybe i will try to fix this on my own. But other things are waiting too ^^
