### ISSUE TITLE
@only annotation matches multiple

### ISSUE THREAD

**Issue by hans-d** [acuminous/yadda#186]
Having a feature 'XYZ' annotated with `@Only`.

Now all features having a name starting with the string of the annotated features are run, instead on only the actual annotated one.
Eg:
- 'XYZ sub 1' is also run
- 'ABC' is not run

Expect only 'XYZ' to run, and not also 'XYZ sub 1'

**Comment by cressie176** [comment]
That's how mocha works unfortunately.
