### ISSUE TITLE
[enhancement] : rerun

### ISSUE THREAD

**Issue by ami44** [acuminous/yadda#189]
Idea : 
add re-run options like cucumber : 

- https://www.relishapp.com/cucumber/cucumber/docs/formatters/rerun-formatter
- https://github.com/cucumber/cucumber-js/blob/master/features/rerun_formatter.feature
- https://github.com/cucumber/cucumber-js#formatters

Thanks
Ami44

**Comment by cressie176** [comment]
Yadda doesn't run your tests for you, so isn't in control of reruns. However if you use mocha I suspect one of the options discussed [here](https://github.com/mochajs/mocha/issues/1515) would work
