### ISSUE TITLE
Disable validate empty scenario, step etc..

### ISSUE THREAD

**Issue by tamascsaba** [acuminous/yadda#191]
I have work in progress feature:

```
@wip
Feature: View Dashboard Page

  Scenario: Simple get Dashboard
```

Yadda throw error:
```
Scenario requires one or more steps
```

I can't configure parser to ignore wip tag :(

**Comment by cressie176** [comment]
Correct - the parser doesn't interpret annotations, it just keeps a list of them and returns them with the scenarios. I'd be reluctant to change this - the parser is already complicated enough and I don't like the idea of some annotations being parser directives, while others are step runner directives.

I'll give the problem some more thought though as adding a "TODO" step isn't very nice.

**Comment by tamascsaba** [comment]
@cressie176 thanks for quick answer :+1:

**Comment by cressie176** [comment]
No new ideas (assuming you want the features / scenarios to be output as pending). Sorry.
