### ISSUE TITLE
JetBrains IDE support

### ISSUE THREAD

**Issue by inf3rno** [acuminous/yadda#196]
Do you plan to support JetBrains IDEs like WebStorm with something like this: https://plugins.jetbrains.com/plugin/7418?pr= ? It parses the `this.When`, `this.Given`, `this.Then` step definitions and by viewing the .feature files it highlights the line we don't have a matching pattern. It looks like this:

![nevtelen](https://cloud.githubusercontent.com/assets/408911/13558130/e56eed78-e3fc-11e5-84a5-a2b9570e653f.png)

To make this work with yadda I am using currently the following workaround:

``` js
var Yadda = require("yadda");
Yadda.plugins.mocha.StepLevelPlugin.init();

var English = Yadda.localisation.English;
var library = English.library();
library.Given = library.given;
library.When = library.when;
library.Then = library.then;

var defineSteps = require(__dirname + "/features/step_definitions/math");
defineSteps.call(library);

new Yadda.FeatureFileSearch(__dirname + "/features").each(function (file) {

    featureFile(file, function (feature) {

        var yadda = Yadda.createInstance(library);

        scenarios(feature.scenarios, function (scenario) {
            steps(scenario.steps, function (step, done) {
                yadda.run(step, done);
            });
        });
    });
}); 
```

and I use the cucumberjs directory structure:

```
|-- features
      |-- x.feature
      |-- step_definitions
            |-- x.js
```

I don't like the directory structure and the uppercase steps, but this highlighting feature is too good to not to be used. :-)

**Comment by inf3rno** [comment]
Andrey Vokin created an issue for us here: https://youtrack.jetbrains.com/issue/WEB-20699 All we need is register and vote on the issue after login, so please vote! 
![nevtelen](https://cloud.githubusercontent.com/assets/408911/13640235/1c9ef982-e614-11e5-9d12-b388369528f2.png)

**Comment by cressie176** [comment]
Thanks for kicking this off. I'll leave the ticket open to encourage votes.

**Comment by cressie176** [comment]
It's been 5 years, and only received 9 votes. Closing
