### ISSUE TITLE
Test script is not windows compatible

### ISSUE THREAD

**Issue by inf3rno** [acuminous/yadda#198]
The current test script `NODE_ENV=test mocha --recursive --reporter spec test` is not Windows compatible. It is possible to make this work with `set NODE_ENV=test&& mocha --recursive --reporter spec test` according to this: http://stackoverflow.com/q/9249830/607033 I tried out, it works on Windows 7. Can you check whether it is Linux compatible?

**Comment by cressie176** [comment]
Doesn't look like it. 

```
var assert = require('assert')

describe('NODE_ENV', function() {

    it.only('should be test', function() {
        assert.equal(process.env.NODE_ENV, 'test')
    })
})

```

```
> NODE_ENV=test mocha --recursive --reporter spec test



  NODE_ENV
    ✓ should be test


  1 passing (11ms)
```

```
> set NODE_ENV=test && mocha --recursive --reporter spec test



  NODE_ENV
    1) should be test


  0 passing (11ms)
  1 failing

  1) NODE_ENV should be test:
     AssertionError: undefined == 'test'
      at Context.<anonymous> (test/NodeEnvTests.js:6:16)
```

**Comment by cressie176** [comment]
However yadda doesn't check NODE_ENV anywhere in the code base and doesn't require any 3rd party libraries that might either. I don't think mocha cares about NODE_ENV so I'd be happy to remove it.

**Comment by inf3rno** [comment]
@cressie176 If it does not have any impact, then please remove it!

**Comment by inf3rno** [comment]
From the scripts:

```
  "scripts": {
    "test": "NODE_ENV=test mocha --recursive --reporter spec test",
    "istanbul": "NODE_ENV=test istanbul cover _mocha -- -u exports --reporter spec",
    "examples": "node bin/examples.js",
    "browserify": "node bin/browserify.js",
    "jshint": "find . -name *.js | grep -vE '/node_modules/|/dist/|/components/|/component-browser/build/|/coverage/|qunit-1.10.0.js' | xargs ./node_modules/.bin/jshint"
  },
```
After we removed the `NODE_ENV`, the istanbul and the jshint certainly does not work. Istanbul does not support windows currently. The jshint contains linux bash code, which is not supported by git bash and webstorm terminal. Cygwin probably supports it. If I remember well the browserify worked and the examples did not work. Can we document that some of these scripts are not working on windows by default, so it is not a bug?

**Comment by cressie176** [comment]
istanbul doesn't work on macs either - at least not with the way the examples are currently setup (with npm link). One of its dependencies follows the links indefinitely.

I also plan to replace jshint with eslint which should resolve the second issue. The important one is npm test, which you kindly fixed. The examples should run on windows however.

**Comment by cressie176** [comment]
istanbul doesn't work on macs either - at least not with the way the examples are currently setup (with npm link). The dependency it uses to find the source files (grok I think) follows the links indefinitely. I'm not convinced by the value of istanbul. I plan to replace jshint with eslint, and will remove grep at the same time. The important one is npm test, which you kindly fixed. 

The examples should run on windows however.

**Comment by inf3rno** [comment]
@cressie176 I don't know why they are not running on Windows. Probably not all of them, just a few has Windows incompatible dependencies or scripts.

**Comment by cressie176** [comment]
I'm not going to get around to this. I don't have a machine capable of running windows.
