### ISSUE TITLE
Always Getting A Timeout On After All Hook With Yadda 

### ISSUE THREAD

**Issue by dheeraj1988** [acuminous/yadda#202]
Error Description :

 1)  "after all" hook:
    Error: timeout of 25000ms exceeded. Ensure the done() callback is being called in this test.
     at null.<anonymous> (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\mocha\lib\runnable.js:215:19)

I dont see any after all hook in implamentation ?

**Comment by cressie176** [comment]
Yadda doesn't configure one. How are you running Yadda? Maybe an issue with Cucumber Boilerplate?

**Comment by cressie176** [comment]
Any luck?
