### ISSUE TITLE
sync/async mix

### ISSUE THREAD

**Issue by chrisns** [acuminous/yadda#205]
it'd be awesome if steps worked the same way mocha tests do:
Where if i do
```
it('test', function(done) {
  doSomeAsyncStuff.then(done);
});
it('test', function() {
  return doSomeAsyncStuff();
});

it('test', function() {
  return assert(true);
});
```
it figures out magically that I gave it the `done` param, or if I return something, and if that return is a promise, it should wait for it to resolve.

where as:
```
.given("$NUM green bottles are standing on the wall", function (num) {
  return wall = new Wall(num);
});

.given("$NUM green bottles are standing on the wall", function (num, done) {
  wall = new Wall(num);
  done();
});

.given("$NUM green bottles are standing on the wall", function (num, done) {
  return doSomeAsyncStuff();
})
```
all rely on different stuff in the
```
    scenarios(feature.scenarios, function (scenario) {
      steps(scenario.steps, function (step, done) {
        yadda.run(step);
      });
    });
```
frustratingly `yadda.run()` doesn't return what the step does, so I can't evaluate what the response is and run the done myself based on the response of the `yadda.run()`

**Comment by cressie176** [comment]
I think I change the Yadda to detect whether an a step is missing a callback (i.e. is synchronous) and execute the callback on it's behalf. I'll have a look this evening. If you want to try it before then, update Macro.js interpret method to

```
    this.interpret = function(step, scenario_context, next) {
        var context = new Context({step:step}).merge(macro_context).merge(scenario_context);
        convert(signature_pattern.groups(step), function(err, args) {
            if (err) return next(err);
            event_bus.send(EventBus.ON_EXECUTE, { step: step, ctx: context.properties, pattern: signature_pattern.toString(), args: args });
            fn.invoke(macro, context.properties, args.concat(next));
            if (macro.length === args.length) next();
        });
    };
```

I don't understand your comment about yadda.run. yadda.run can execute a single, or multiple steps, so when passed an array I would have to decide how best to return multiple results (probably as an array too). It would also be a bit odd to return a value from asynchronous steps.

I did consider this feature when first implementing yadda but decided against it since the steps can update a context passed in as the second parameter to yadda.run

**Comment by chrisns** [comment]
Hey!
Thanks for the speedy response, the `interpret` as you say is clearly the right place to put the logic as apposed to trying to shoehorn it into stuff around the `yadda.run`.

I'll give your suggestion a go later, but it looks like it should make sense for most cases.

Async steps should ideally be able to return a promise and have the `next()` called in a `.then()` or maybe `.finally()` on the end of the promise chain.
if async steps weren't able to return the promise, every 'promisey' type step would have to look like:

```
.given("$NUM green bottles are standing on the wall", function (num, next) {
  Promise.resolve('foo').finally(next);
})
```

which is probably fine, it's just going to cause a lot of unnecessary imho duplication as opposed to:
```
.given("$NUM green bottles are standing on the wall", function (num) {
  return Promise.resolve('foo');
});
```
or in more succinct es6:
```
.given("$NUM green bottles are standing on the wall", num =>
  Promise.resolve('foo')
);
```

**Comment by cressie176** [comment]
I'm not a fan of promises.

**Comment by chrisns** [comment]
sad face!
even in the native es2015/es6 sense?
if that's a no go, perhaps we/you could have a snippet to use in one's own `test.js` that would intercept to handle promises and run the `next()`?
I'll try to put something together this evening and make a PR for you to consider.

**Comment by cressie176** [comment]
All good. Thanks for the PRs.
