### ISSUE TITLE
Error handling in async steps

### ISSUE THREAD

**Issue by provegard** [acuminous/yadda#211]
When an async step fails with an error, the `next` function won't be automatically called by Yadda, causing a test timeout without error information. Consider the following example:

```
.when("foobar", function (next) {
  if (true) throw new Error("ugh");
  next();
});
```
I had thought that Yadda would catch the error and invoke `next` for me with the Error, but it doesn't. I tried to modify Yadda as follows:

```
    this.interpret = function(step, scenario_context, next) {
        var context = new Context({step:step}).merge(macro_context).merge(scenario_context);
        convert(signature_pattern.groups(step), function(err, args) {
            if (err) return next(err);
            event_bus.send(EventBus.ON_EXECUTE, { step: step, ctx: context.properties, pattern: signature_pattern.toString(), args: args });
            // **** try-catch around fn.invoke added
            try {
                fn.invoke(macro, context.properties, args.concat(next));
            } catch (e) {
                next(e);
            }
        });
    };

```

This works a lot better as it allows me to see the error right away.

Does it make sense to incorporate my fix into Yadda? If not, is there any way for me to wrap step functions that doesn't involve monkey-patching the library functions? I would like to avoid adding try-catch manually to all step functions.

**Comment by cressie176** [comment]
Hi. Seems reasonable but wouldn't help if the asynchronous part of the test threw an error. I've never seen this cause timeouts - i usually run my tests via mocha and the exception is handled for me. How are you running your tests?

**Comment by cressie176** [comment]
I pushed an testcase to a branch [here](https://github.com/acuminous/yadda/blob/issue-211/examples/mocha-async/bottles-library.js#L38), however mocha deals with the error as I would expect

**Comment by cressie176** [comment]
```
Mocha Asynchronous Example
    A bottle falls from the wall
      ✓ Given a 6 foot wall 
      ✓ Given 100 green bottles are standing on the wall 
      ✓ when 1 green bottle accidentally falls 
      1) then there are 99 green bottles standing on the wall
    No bottles are left
      ✓ Given a 6 foot wall 
      ✓ Given 1 green bottles are standing on the wall 
      ✓ when 1 green bottle accidentally falls 
      2) then there are 0 green bottles standing on the wall
    Bottles are reset
      - Given a 6 foot wall
      - Given there are no green bottles
      - when 5 minutes has elapsed
      - then there are 100 green bottles standing on the wall
    100 bottles are standing on a wall
      ✓ Given a 6 foot wall 
      ✓ Given 100 green bottles are standing on the wall 
      ✓ when 1 green bottle accidentally falls 
      3) then there are 99 green bottles standing on the wall
    99 bottles are standing on a wall
      ✓ Given a 6 foot wall 
      ✓ Given 99 green bottles are standing on the wall 
      ✓ when 1 green bottle accidentally falls 
      4) then there are 98 green bottles standing on the wall
    10 bottles are standing on a wall
      ✓ Given a 6 foot wall 
      ✓ Given 10 green bottles are standing on the wall 
      ✓ when 1 green bottle accidentally falls 
      5) then there are 9 green bottles standing on the wall


  15 passing (85ms)
  4 pending
  5 failing

  1) Mocha Asynchronous Example A bottle falls from the wall then there are 99 green bottles standing on the wall:
     Uncaught Error: foo
      at null._onTimeout (/Users/steve/Development/acuminous/yadda/examples/mocha-async/bottles-library.js:38:19)
      at Timer.listOnTimeout (timers.js:92:15)

  2) Mocha Asynchronous Example No bottles are left then there are 0 green bottles standing on the wall:
     Uncaught Error: foo
      at null._onTimeout (/Users/steve/Development/acuminous/yadda/examples/mocha-async/bottles-library.js:38:19)
      at Timer.listOnTimeout (timers.js:92:15)

  3) Mocha Asynchronous Example 100 bottles are standing on a wall then there are 99 green bottles standing on the wall:
     Uncaught Error: foo
      at null._onTimeout (/Users/steve/Development/acuminous/yadda/examples/mocha-async/bottles-library.js:38:19)
      at Timer.listOnTimeout (timers.js:92:15)

  4) Mocha Asynchronous Example 99 bottles are standing on a wall then there are 98 green bottles standing on the wall:
     Uncaught Error: foo
      at null._onTimeout (/Users/steve/Development/acuminous/yadda/examples/mocha-async/bottles-library.js:38:19)
      at Timer.listOnTimeout (timers.js:92:15)

  5) Mocha Asynchronous Example 10 bottles are standing on a wall then there are 9 green bottles standing on the wall:
     Uncaught Error: foo
      at null._onTimeout (/Users/steve/Development/acuminous/yadda/examples/mocha-async/bottles-library.js:38:19)
      at Timer.listOnTimeout (timers.js:92:15)



npm ERR! Test failed.  See above for more details.
```

**Comment by provegard** [comment]
I'm running using Jasmine inside Nashorn (so I have patched Yadda slightly to be able to load in Nashorn). I'll put together a repo that demonstrates the problem.

**Comment by cressie176** [comment]
> Nashorn is a JavaScript engine developed in the Java programming language by Oracle.

I'm so sorry!

**Comment by provegard** [comment]
I'm sorry for not responding - I missed this completely, and just got an e-mail about the issue being closed.

I pushed a repro here:

https://github.com/provegard/yadda/commit/bce15ce56b795a2cba44d04b8ff6e656ae6deaa7

When I run the tests using `karma start --single-run` (so no Nashorn), I get an exception:

```
PhantomJS 2.1.1 (Windows 8 0.0.0) Yadda should handle an error in an asynchronous scenario FAILED
        no next
```

I.e., the error is caught by the test framework, but not by Yadda itself.

When running the Yadda tests, this is not a big deal, but in the original situation where I encountered this, I got a test timeout rather than fail-fast behavior. Fail-fast behavior is preferred.

**Comment by cressie176** [comment]
Hi,
Thanks for pushing the example. I understand the issue but there's only so much Yadda can do about it. Wrapping the step execution inside a try and catch will help for 'faux' asynchronous steps, i.e. those which take a callback, but aren't actually asynchronous, but for truly asynchronous functions such as the one below, the only way Yadda would be able to catch all errors is to invoke the function from within a domain. I don't want to do this as domains are deprecated, and won't work in non node environments.

```
    .when("$NUM green bottle accidentally falls", function (number_of_falling_bottles, next) {
      try {
        setImmediate(function() {
          throw new Error()
          wall.fall(number_of_falling_bottles);
          next()
        })
      } catch(err) {
        next(err)
      }
    })
```

I don't mind wrapping the function call in a try / catch to handle the 'faux' async case though

**Comment by cressie176** [comment]
Added a try / catch which will catch errors thrown before the step goes asynchronous. Can't do much more than this without domains.

**Comment by provegard** [comment]
You're right, my original use case is what you call "faux" async. Try/catch sounds fine!
