### ISSUE TITLE
Report unused step definitions

### ISSUE THREAD

**Issue by dan-searle** [acuminous/yadda#213]
Is there a way of getting Yadda to report step definitions that have been loaded but have not been used by any feature scenarios?

Thanks

**Comment by cressie176** [comment]
There's nothing built in to Yadda for this and I agree it would be a nice feature, however I'm not sure it's feasible. One of the benefits of yadda is that you can selectively load libraries and choose which features to execute, so not all steps will be be executed for every test run.

**Comment by dan-searle** [comment]
I understand. I wonder if it's possible to support this by adding a means to query Yadda for steps run, and for steps loaded - and leave it up to the user to decide what to do with that information.

**Comment by cressie176** [comment]
I was thinking along the same lines. You can already get the steps run by listening to the [ON_STEP](https://github.com/acuminous/yadda/blob/6121e9438a9e4349061e730cafe2370a93ea99f1/lib/Interpreter.js#L73) or [ON_EXECUTE](https://github.com/acuminous/yadda/blob/master/lib/Macro.js#L49) event. It should be easy to add an ON_STEP_LOAD event emitted in the same way

**Comment by cressie176** [comment]
Available in 0.17.8. I added an [example](https://github.com/acuminous/yadda/blob/master/examples/report-unused-steps/test.js#L11-L16) showing how it can be used
