### ISSUE TITLE
Yadda in bower.io packages

### ISSUE THREAD

**Issue by sfbwalder** [acuminous/yadda#214]
Would it be possible for you to publish this out to the bower.io package registry?

We are working being a corporate filewall going through private-bower, and so going direct to github does not work for us.

**Comment by cressie176** [comment]
Will do

**Comment by cressie176** [comment]
Give that a go.

**Comment by cressie176** [comment]
I might need to rev one more time

**Comment by cressie176** [comment]
OK - bower.json in sync with github tags now. Hopefully 0.17.9 is ok.

**Comment by sfbwalder** [comment]
Thanks! I can now install directly.  We are using Ember, and the ember-cli-yadda add-on is setting up bower.json to use acuminous/yadda, so I will open an issue there and hopefully we will see it work through the add-on.
