### ISSUE TITLE
node-v6.2.0: DeprecationWarning: 'GLOBAL' is deprecated, use 'global'.

### ISSUE THREAD

**Issue by michael-donat** [acuminous/yadda#215]
Not sure whether this comes out from a dependency or yadda itself.

We do run it via babel/register.

**Comment by cressie176** [comment]
Thanks for reporting. It's from yadda, but only gets emitted with certain versions of node. I just need to rename it.

**Comment by cressie176** [comment]
Renaming global to lower case breaks karma
