### ISSUE TITLE
Catch thenable exceptions

### ISSUE THREAD

**Issue by krivin** [acuminous/yadda#217]
Love yadda! Love support for thenables, https://github.com/acuminous/yadda/commit/d1c5c63855e63dd606d97ae68b55062399ce0f3f#diff-d2708c4b2779758848a0614156e0d22fR51. However, should there not also be a .catch(e) { next(e); } in there?

**Comment by cressie176** [comment]
You mean [here](https://github.com/acuminous/yadda/blob/master/lib/Macro.js#L51-L53)?

**Comment by krivin** [comment]
Yes. Sorry for the bad link.

**Comment by cressie176** [comment]
Should be fixed in 0.18.0
