### ISSUE TITLE
I don't get error messages

### ISSUE THREAD

**Issue by inf3rno** [acuminous/yadda#220]
I use this code to test with Yadda Cucumber.js style. So the feature files are in the `/features` directory, and the step definition files are in the `/features/step_definitions` directory and have the same basename as the features.

```js
var Yadda = require("yadda");
Yadda.plugins.mocha.StepLevelPlugin.init();

var English = Yadda.localisation.English;

var path = Yadda.shims.path;

new Yadda.FeatureFileSearch("./features").each(function (file) {

    featureFile(file, function (feature) {

        var stepsFile = String("./" + path.dirname(file) + "/step_definitions/" + path.basename(file, ".feature")).split("\\").join("/");

        var library = English.library();
        library.Given = library.given;
        library.When = library.when;
        library.Then = library.then;
        // note: Making compatible with the Intellij cucumber plugin

        var defineSteps = require(stepsFile);
        defineSteps.call(library);

        var yadda = Yadda.createInstance(library);

        scenarios(feature.scenarios, function (scenario) {
            steps(scenario.steps, function (step, done) {
                yadda.run(step, done);
            });
        });
    });
});
```

My problem is that I don't get relevant error messages from the CLI reporter when a test fails. I just got the scenario title, and that's all, it exits. Is there a way to get a stack trace somehow?

**Comment by cressie176** [comment]
What type of test failure is it? I get stack traces for exceptions and assertion failures.

**Comment by inf3rno** [comment]
@cressie176 Nothing works here, I just tested it with a simple `throw new Error("xxx")`. What is interesting, that this is a node.js only issue. By using karma I got the stack.

**Comment by inf3rno** [comment]
Hmm I don't get it by Chrome either. I use a lib, which overrides the `Error.prepareStackTrace` and replaces the stack string with an object, which has a `toString()` method. Maybe that is the cause of the problem.

**Comment by inf3rno** [comment]
I got some error probably related to stack string generation, so maybe the lib has a bug. I need time to find the cause, I check in later.

**Comment by inf3rno** [comment]
I found it.

```
PhantomJS 2.1.1 (Windows 7 0.0.0) building stones reading without data leads to failure Then I should not be able to read data from it FAILED
        undefined is not a constructor (evaluating 'stack.split('\n')')
```

Some lib is trying to do `error.stack.split("\n")`, and the actual stack object does not have a split method. Using `String(error.stack).split("\n")` would solve it, or adding String methods to the stack object would do the same.

**Comment by inf3rno** [comment]
I close this, sorry for the false positive.
