### ISSUE TITLE
Any suggestions for implementing factories?

### ISSUE THREAD

**Issue by FarhadG** [acuminous/yadda#226]
We're currently using a `mock data` solution where we're testing against a set of data points, however, it's getting quite difficult to manage and I was wondering if we have any good solutions or suggestions for implementing `factories` where we create the test data on the fly (or any other viable solutions).

**Comment by cressie176** [comment]
I usually roll my own solution using a combination of the [builder(https://en.wikipedia.org/wiki/Builder_pattern) and [Object Mother](http://martinfowler.com/bliki/ObjectMother.html) patterns. I'm always careful to generate random values for anything I'm not asserting. I've found [chance](http://chancejs.com/) quite useful for this.

**Comment by FarhadG** [comment]
Thanks for the response, @cressie176. Would you happen to have any code I can look at in regards to Yadda?

**Comment by cressie176** [comment]
No sorry.
