### ISSUE TITLE
Add Ava Example

### ISSUE THREAD

**Issue by esteban-uo** [acuminous/yadda#227]
Hi! thanks a lot for Yadda, I really love it!

Any chance to create an example/plugin for Ava? https://github.com/avajs/ava 

Thanks!

**Comment by cressie176** [comment]
Glad you like Yadda, and thanks for the suggestion of an Ava example/plugin. I'll give it some consideration, but won't have time until the new year. Feel free to have a go in the meantime.

**Comment by FranzSkuffka** [comment]
Bumpity!

**Comment by cressie176** [comment]
Sorry - I've decided not to add anymore examples. They're too hard to support over time.
