### ISSUE TITLE
ya-done

### ISSUE THREAD

**Issue by moogus** [acuminous/yadda#228]
#### [ya-done npm package](https://www.npmjs.com/package/ya-done)

Hi

Big fan of yadda, started by using it in ember.

I put a npm package together for the QA's at work (British Gas) so they could get a simple webdriver BDD set-up working. I've managed to talk BG into open sourcing the package.  Wondered if you could mention it for me in either the docs or readme.

The aim of the package is to provide a built solution for yadda with chai, mocha, webdriver for both phantomjs and chromedriver. 

Regards

Darren

**Comment by cressie176** [comment]
Glad you're finding Yadda useful and thanks for letting me know about ya-done. I'll add it to [the list](https://acuminous.gitbooks.io/yadda-user-guide/content/en/getting-started/functional-testing.html) of third party frameworks

**Comment by moogus** [comment]
Amazing thanks!! 

Centrica (British Gas) are heavily using both yadda and ya-done.

**Comment by cressie176** [comment]
gitbook updated. Cheers.
