### ISSUE TITLE
Request: auto retry support

### ISSUE THREAD

**Issue by GaryAlway** [acuminous/yadda#230]
Would be great to have an auto failed test retry option.
Webdriver tests can be so flakey.
Thanks for considering.

**Comment by cressie176** [comment]
Hi Gary,
Yadda doesn't run your tests, so if whatever you have under the hood supports re-runs then you might be able to get it to work. I can imagine reseting the context to the correct state might be tricky though.

See https://github.com/acuminous/yadda/issues/189
