### ISSUE TITLE
ya-done-appium

### ISSUE THREAD

**Issue by moogus** [acuminous/yadda#234]
### ya-done-appium

Hi

I created the package [ya-done](https://www.npmjs.com/package/ya-done) for webdriver testing.

Can you please add my new npm package I'm currently working on for mobile BDD projects using appium [ya-done-appium](https://www.npmjs.com/package/ya-done-appium) to you [user-guide-functional-testing page](https://acuminous.gitbooks.io/yadda-user-guide/en/getting-started/functional-testing.html)

It's still in _alpha_ but I will to have it all figured out in the next few days. 

Thanks Darren

**Comment by moogus** [comment]
Hi this is fully functional now

**Comment by cressie176** [comment]
Very cool. Will update the user guide, and close when done. Sorry - not sure why I didn't see the issue when you opened it 8 days ago.

**Comment by cressie176** [comment]
Done. Sorry it took so long. Just started a new job, and still catching up.
