### ISSUE TITLE
Composing steps?

### ISSUE THREAD

**Issue by lolmaus** [acuminous/yadda#236]
Hi!

Yadda allows inheriting step definitions. This is very convenient.

For example, I have a page with two tabs, so I create two Gherkin features and two Steps files. But there are steps that are shared across both tabs: some basic assertions and most of setup. To resolve this problem I create an intermediate Steps file (nesting illustrates inheritance):

* `steps.js`
  * `code-review-steps.js`
    * `code-review-discussion-tab-steps.js`
    * `code-review-changes-tab-steps.js`

This works fine so far.

But then I run into a more complicated use case. I have a large epic that involves multiple pages. I want to test those pages in combination: start on page M, then do something on page K, then assert page Z has certain results. There are multiple scenarios that involve multiple pages in various combinations.

Step inheritance can't resolve this problem. I need step composition: an ability to import steps from several files.

The root of the problem is the API based on method chains. I've been thinking of a possible solution and the only thing I could come up with is using an array of step descriptor objects:

```js
[
  {
    method: 'when',
    matcher: "user clicks on the (Expand|Collapse) All Outdated Files button",
    callback (button) { /*...*/ },
    options: {},
  },
  {
    method: 'then',
    matcher: "there should be (\\w+) line comment groups",
    callback (button) { /*...*/ },
    options: {},
  },
]
```

Looks ugly, but it allows concatenating multiple descriptor arrays in any combination, and then iterating over them and call the API.

If the project is not using step options and RegExp objects, then array can be simplified to a hash like this:

```js
{
  "when user clicks on the (Expand|Collapse) All Outdated Files button" (button) { /*...*/ },
  "there should be (\\w+) line comment groups" (count) { /*...*/ },
}
```

This looks even cleaner than the method chaining API. :sunglasses: 

Implementing a custom step composer based on this approach is no biggie. The goal of this issue is to:
* See if Yadda maintainers acknowledge the problem.
* Discus my solution.
* Discus alternative solutions.
* Provide examples for the community to reuse.
* Look into possible ways of resolving the problem in the library, rather than forcing users to figure it out on their own.

**Comment by cressie176** [comment]
Thanks for your suggestion - I agree it's always better to start off things like this with a discussion. I'll give it some thought and respond.

**Comment by cressie176** [comment]
When you say you're inheriting steps, do you literally mean prototypal inheritance? I'd never actually considered doing this.

Instead I've always composed an array of step libraries, which may be the exact feature you're asking for...
```
const libraries = [
  require('./libraries/tab1'),
  require('./libraries/tab2),
  require('./libraries/common'),
]
const yadda = Yadda.createInstance(libraries);
```

When you have a large testsuite steps in one library can end up clashing with steps in another. Yadda tries hard to avoid this not only by matching the step text against the pattern, but also by scoring a parameter free version of the text against pattern using the longest common sequence algorithm. If it still there's still no clear winner then it will prefer a step from the library it used most recently. If the step didn't come from the most recent library Yadda emits an ambiguous step error.

One way to minimise these is to only compose steps necessary for the feature. You could do this by annotating features with a list of step libraries, or my managing an external mapping between feature name and step libraries.

Let me know if this does what you need.

**Comment by lolmaus** [comment]
I'm using the [ember-cli-yadda](https://github.com/albertjan/ember-cli-yadda) EmberJS addon.

It maps a feature file to a steps file. I. e. when `ember-cli-yadda` runs a specific feature, it automatically loads one specific steps file. From the steps file you are supposed to export a library with chained methods applied to it.

By inheritance I mean importing a library from one steps file into another and continuing the chain of methods in the second file.

In the first file you have the most general steps that a required by most features:

```js
// steps.js
export default yadda.localization.English.library().given().when().then()
```

and in the second file you add steps specific to the feature:

```js
// my-feature-steps.js
import firstFile from './steps'
export default firstFile.when().then().then()
```

Since the feature file is mapped to a single specific steps file, this way lets you inherit only a linear succession of steps files, similar to how a subfolder cannot be placed into more than one sibling folder.

From what you say it looks like Yadda does provide low-level features necessary to achieve composition from multiple sources, and it's the `ember-cli-yadda` implementation that's limiting me. CC @remkoboschker, @simonihmig, @mschinis, @albertjan

The limiting factor is that I'm supposed to export a single library. @cressie176 Is there a way to apply steps from one library to another? Something like `library1.import(library2)`?

**Comment by simonihmig** [comment]
It is possible, and we do this quite often. The approach we took is to not only have a default export with the final library, but also have a named export with a function that takes a library and returns one (with the applied steps). Something like that:

```js
// foo-steps.js
import baseSteps from './steps';

export function steps(steps) {
  return steps
    .when('foo', function() {
      // implement foo
    });
}

export default function() {
  return steps(baseSteps());
}
```

Then you can import that in `bar-steps.js`:

```js
// bar-steps.js
import baseSteps from './steps';
import { steps as fooSteps } from './foo-steps';

export function steps(steps) {
  return steps
    .then('bar', function() {
      // implement bar
    });
}

export default function() {
  return steps(fooSteps(baseSteps()));
}
```

In the bar feature, you while have `when foo` as well `then bar` available, as well as everything from the base steps (`steps.js`). Does that answer your question?

**Comment by lolmaus** [comment]
@simonihmig Yes! And it is closer to Yadda API than my solution with an array/hash. Thank you. :bow:

@cressie176 Feel free to close this, unless you want to keep the discussion going.

**Comment by cressie176** [comment]
thanks @simonihmig
