### ISSUE TITLE
Is it possible yadda with electron-spectrum?

### ISSUE THREAD

**Issue by ZHChen8397** [acuminous/yadda#239]
Hi,
I am writing ap electron app and tried to test it with yadda.
this is the original index

new Yadda.FeatureFileSearch('./test/features').each(function(file) {

    featureFile(file, function(feature) {

        var libraries = require_feature_libraries(feature);
        var yadda = Yadda.createInstance(libraries);

        scenarios(feature.scenarios, function(scenario) {

            steps(scenario.steps, function(step,done) {

                yadda.run(step,done);
            });
        });
    });
    });

Is it possible that before every feature I can start my app?
the code may be like 

    new Yadda.FeatureFileSearch('./test/features').each(function(file) {

        featureFile(file, function(feature) {
            beforeEach(function () {
                this.app = new Application({

                  path: electronPath,
        
              args: [path.join(__dirname, '..')]
            })
            return this.app.start()
          })
        var libraries = require_feature_libraries(feature);
        var yadda = Yadda.createInstance(libraries);

        scenarios(feature.scenarios, function(scenario) {

            steps(scenario.steps, function(step,done) {

                yadda.run(step,done);
            });
        });
        afterEach(function () {
            if (this.app && this.app.isRunning()) {
              return this.app.stop()
            }
          })
    });
});

**Comment by cressie176** [comment]
Any luck getting it working?
