### ISSUE TITLE
docstring

### ISSUE THREAD

**Issue by ami44** [acuminous/yadda#53]
is it possible to write this with yadda ?:

    Scenario:
      Given a blog post named "Random" with:
        """
        Some Title, Eh?
        ===============
        Here is the first paragraph of my blog post.
        Lorem ipsum dolor sit amet, consectetur adipiscing
        elit.
     """
        
src : 
- http://asymmetrical-view.com/2011/06/02/cucumber-gherkin-and-multiline-arguments.html
- http://docs.behat.org/guides/1.gherkin.html#pystrings
- http://cukes.info/step-definitions.html
    
Ami44

**Comment by cressie176** [comment]
Going to close as discussed in #144
