### ISSUE TITLE
duplicate annotation for @Pending

### ISSUE THREAD

**Issue by simoami** [acuminous/yadda#87]
The annotation map contains 2 entries for "pending". Is it possible to reduce to a single entry?

**Comment by cressie176** [comment]
Thinking about lower casing all annotations, thereby removing the duplicates

**Comment by simoami** [comment]
sounds like a good plan.

**Comment by cressie176** [comment]
Working on an alternative. The annotations handling code in FeatureParser wasn't very DRY some I'm creating an Annotations class.

```js
scenario.annotations.each(function(annotation) {
   console.log(annotation.key, annotation.value)
})

scenario.annotations.get('pending') === scenario.annotations.get('Pending')
```

Appreciate this would require a change to mimik. Would that be a problem and is there anything else you'd like me to add to the Annotations class? (prefer not to expose the underlying annotations map).

**Comment by cressie176** [comment]
Had to forego the new annotations api - caused problems with LateRooms moonraker. I've reduced the map to a single, lowercased entry.
